// Players with a "goal" portrait in /public/goal-images.
// Auto-generated from the image filenames (<Player Name>-goal.webp).
// Used for the goal-celebration popup when that player scores during a match.

export const GOAL_IMAGE_NAMES: ReadonlySet<string> = new Set([
  "Achraf Hakimi",
  "Alfredo Di Stéfano",
  "Alan Hansen",
  "Alessandro Nesta",
  "Alessandro Del Piero",
  "Alphonso Davies",
  "Amancio Amaro",
  "Andrés Iniesta",
  "Andreas Möller",
  "Andriy Shevchenko",
  "Andrea Pirlo",
  "Andy Cole",
  "Antonio Rüdiger",
  "Arjen Robben",
  "Ashley Cole",
  "Ángel Di María",
  "Álvaro Morata",
  "Anton Janssen",
  "Armando Picchi",
  "Bernardo Silva",
  "Billy McNeill",
  "Bradley Barcola",
  "Bobby Charlton",
  "Bobby Murdoch",
  "Carlos Tévez",
  "Casemiro",
  "Cesare Maldini",
  "Christian Pulisic",
  "Clarence Seedorf",
  "Cristiano Ronaldo",
  "Dani Alves",
  "Dani Carvajal",
  "Danny Blind",
  "David Alaba",
  "David Beckham",
  "David Villa",
  "Dejan Savićević",
  "Denis Law",
  "Deco",
  "Désiré Doué",
  "Didier Drogba",
  "Diego Milito",
  "Dwight Yorke",
  "Edgar Davids",
  "Erling Haaland",
  "Eusébio",
  "Fabinho",
  "Fabián Ruiz",
  "Ferenc Puskás",
  "Federico Valverde",
  "Fernando Hierro",
  "Fernando Redondo",
  "Filippo Inzaghi",
  "Franco Baresi",
  "Frank Lampard",
  "Frank Rijkaard",
  "Franck Ribéry",
  "Francisco Gento",
  "Franz Beckenbauer",
  "Gaetano Scirea",
  "Gareth Bale",
  "Gerard Piqué",
  "Gennaro Gattuso",
  "George Best",
  "Gerd Müller",
  "Giacinto Facchetti",
  "Gianni Rivera",
  "Gianluca Vialli",
  "Giovanni Trapattoni",
  "Gonçalo Ramos",
  "Graeme Souness",
  "Hakim Ziyech",
  "Héctor Rial",
  "Hristo Stoichkov",
  "Fernando Morientes",
  "Fernando Torres",
  "Ilie Bărbulescu",
  "İlkay Gündoğan",
  "Ian Rush",
  "Isco",
  "Ivan Perišić",
  "Jack Grealish",
  "Javier Mascherano",
  "Javier Zanetti",
  "Jimmy Johnstone",
  "Johan Cruyff",
  "Johan Neeskens",
  "Johnny Rep",
  "John Robertson",
  "João Neves",
  "Jorginho",
  "Joselu",
  "Joshua Kimmich",
  "Juan Mata",
  "Jude Bellingham",
  "Julián Álvarez",
  "Jérôme Boateng",
  "José Altafini",
  "José Augusto",
  "José Águas",
  "Kai Havertz",
  "Karim Benzema",
  "Karl-Heinz Schnellinger",
  "Kaká",
  "Kenny Dalglish",
  "Kevin Keegan",
  "Khvicha Kvaratskhelia",
  "Kevin De Bruyne",
  "Kingsley Coman",
  "Leon Goretzka",
  "Lionel Messi",
  "Luka Modrić",
  "Lúcio",
  "Luís Figo",
  "Luis Suárez",
  "Maicon",
  "Marco Asensio",
  "Marcelo",
  "Marcel Desailly",
  "Marquinhos",
  "Mario Balotelli",
  "Marco Materazzi",
  "Marco van Basten",
  "Marin Radu",
  "Mario Mandžukić",
  "Mario Gómez",
  "Matthias Sammer",
  "Michel Platini",
  "Michael Laudrup",
  "Miguel Muñoz",
  "Mohamed Salah",
  "Mário Coluna",
  "N'Golo Kanté",
  "Nemanja Vidić",
  "Neymar",
  "Nicolas Anelka",
  "Nuno Mendes",
  "Nwankwo Kanu",
  "Olivier Giroud",
  "Ousmane Dembélé",
  "Ove Kindvall",
  "Paolo Maldini",
  "Patrick Kluivert",
  "Paul Breitner",
  "Paul Scholes",
  "Paulo Futre",
  "Philipp Lahm",
  "Philippe Coutinho",
  "Phil Foden",
  "Phil Neal",
  "Piet Keizer",
  "Pirri",
  "Predrag Mijatović",
  "Pierino Prati",
  "Rabah Madjer",
  "Raphaël Varane",
  "Raúl",
  "Raymond Kopa",
  "Robert Lewandowski",
  "Roberto Firmino",
  "Ronaldinho",
  "Ronald Koeman",
  "Rio Ferdinand",
  "Rivaldo",
  "Riyad Mahrez",
  "Rodri",
  "Rodrygo",
  "Roberto Carlos",
  "Rui Costa",
  "Rúben Dias",
  "Ruud Gullit",
  "Ruud Krol",
  "Roy Keane",
  "Ryan Giggs",
  "Sadio Mané",
  "Samuel Eto'o",
  "Sandro Mazzola",
  "Sergio Ramos",
  "Serge Gnabry",
  "Steven Gerrard",
  "Sávio",
  "Thomas Müller",
  "Thierry Henry",
  "Thiago Alcântara",
  "Thiago Silva",
  "Timo Werner",
  "Toni Kroos",
  "Tarcisio Burgnich",
  "Terry McDermott",
  "Tommy Gemmell",
  "Trent Alexander-Arnold",
  "Trevor Francis",
  "Uli Hoeneß",
  "Virgil van Dijk",
  "Warren Zaïre-Emery",
  "Wayne Rooney",
  "Wesley Sneijder",
  "Willem van Hanegem",
  "Willian Pacho",
  "Vinícius Júnior",
  "Vitinha",
  "Xavi",
  "Yaya Touré",
  "Zbigniew Boniek",
  "Zinedine Zidane",
]);

export function hasGoalImage(name: string): boolean {
  return GOAL_IMAGE_NAMES.has(name);
}

export function goalImageSrc(name: string): string {
  return `/goal-images/${encodeURIComponent(name)}-goal.webp`;
}
