// AUTO-GENERATED from the rebalanced squad CSV. Do not edit by hand.
// pos = primary role; alt = secondary roles. A player can fill any of them.

export type RawPlayer = { name: string; pos: string; alt?: string[]; rating: number };

export const ROSTERS: Record<string, RawPlayer[]> = {
  "psg-2025": [
    { name: "Khvicha Kvaratskhelia", pos: "PE", alt: ["ME"], rating: 90 },
    { name: "Ousmane Dembélé", pos: "PD", alt: ["MD", "ATA"], rating: 88 },
    { name: "Vitinha", pos: "MC", alt: ["MEI"], rating: 87 },
    { name: "Achraf Hakimi", pos: "LD", alt: ["MD", "PD"], rating: 86 },
    { name: "João Neves", pos: "MC", alt: ["VOL"], rating: 85 },
    { name: "Nuno Mendes", pos: "LE", alt: ["ME"], rating: 84 },
    { name: "Marquinhos", pos: "ZAG", alt: ["VOL"], rating: 84 },
    { name: "Désiré Doué", pos: "MEI", alt: ["MC", "ATA"], rating: 84 },
    { name: "Willian Pacho", pos: "ZAG", rating: 83 },
    { name: "Bradley Barcola", pos: "PE", alt: ["ME"], rating: 82 },
    { name: "Warren Zaïre-Emery", pos: "MC", rating: 80 },
    { name: "Fabián Ruiz", pos: "MC", alt: ["VOL"], rating: 79 },
    { name: "Matvei Safonov", pos: "GOL", rating: 79 },
    { name: "Lucas Hernández", pos: "LE", alt: ["ZAG"], rating: 77 },
    { name: "Gonçalo Ramos", pos: "ATA", rating: 77 },
    { name: "Kang-in Lee", pos: "MEI", alt: ["MC"], rating: 76 },
    { name: "Lucas Beraldo", pos: "ZAG", alt: ["LD"], rating: 76 },
  ],
  "psg-2024": [
    { name: "Ousmane Dembélé", pos: "PD", alt: ["MD", "ATA"], rating: 93 },
    { name: "Gianluigi Donnarumma", pos: "GOL", rating: 89 },
    { name: "Khvicha Kvaratskhelia", pos: "PE", alt: ["ME"], rating: 88 },
    { name: "Désiré Doué", pos: "MEI", alt: ["MC", "PE"], rating: 87 },
    { name: "Achraf Hakimi", pos: "LD", alt: ["MD", "PD"], rating: 86 },
    { name: "Marquinhos", pos: "ZAG", alt: ["VOL"], rating: 85 },
    { name: "Nuno Mendes", pos: "LE", alt: ["ME"], rating: 84 },
    { name: "Vitinha", pos: "MC", alt: ["MEI"], rating: 84 },
    { name: "Fabián Ruiz", pos: "MC", alt: ["VOL"], rating: 84 },
    { name: "Bradley Barcola", pos: "PE", alt: ["ME"], rating: 84 },
    { name: "Willian Pacho", pos: "ZAG", rating: 84 },
    { name: "João Neves", pos: "MC", alt: ["VOL"], rating: 82 },
    { name: "Warren Zaïre-Emery", pos: "MC", rating: 81 },
    { name: "Gonçalo Ramos", pos: "ATA", rating: 81 },
    { name: "Lucas Hernández", pos: "ZAG", alt: ["LE"], rating: 80 },
    { name: "Lucas Beraldo", pos: "ZAG", rating: 79 },
    { name: "Kang-in Lee", pos: "MEI", alt: ["MC"], rating: 78 },
    { name: "Matvei Safonov", pos: "GOL", rating: 78 },
  ],
  "rm-2023": [
    { name: "Vinícius Júnior", pos: "PE", alt: ["ME", "ATA"], rating: 93 },
    { name: "Luka Modrić", pos: "MC", alt: ["MEI"], rating: 87 },
    { name: "Toni Kroos", pos: "MC", alt: ["VOL"], rating: 86 },
    { name: "Federico Valverde", pos: "MC", alt: ["VOL", "LD"], rating: 90 },
    { name: "Jude Bellingham", pos: "MEI", alt: ["MC", "ATA"], rating: 92 },
    { name: "Rodrygo", pos: "PD", alt: ["MD", "ATA"], rating: 84 },
    { name: "Antonio Rüdiger", pos: "ZAG", rating: 83 },
    { name: "Andriy Lunin", pos: "GOL", rating: 82 },
    { name: "Aurélien Tchouaméni", pos: "VOL", alt: ["MC"], rating: 81 },
    { name: "Éder Militão", pos: "ZAG", alt: ["LD"], rating: 80 },
    { name: "Thibaut Courtois", pos: "GOL", rating: 79 },
    { name: "Dani Carvajal", pos: "LD", alt: ["MD"], rating: 79 },
    { name: "Eduardo Camavinga", pos: "VOL", alt: ["MC"], rating: 79 },
    { name: "Brahim Díaz", pos: "MEI", alt: ["PD", "ATA"], rating: 79 },
    { name: "Lucas Vázquez", pos: "LD", alt: ["MD"], rating: 78 },
    { name: "Joselu", pos: "ATA", rating: 78 },
    { name: "Nacho Fernández", pos: "ZAG", rating: 77 },
    { name: "Arda Güler", pos: "MEI", alt: ["MC", "PE"], rating: 77 },
    { name: "Ferland Mendy", pos: "LE", alt: ["ME"], rating: 77 },
  ],
  "mci-2022": [
    { name: "Erling Haaland", pos: "ATA", rating: 96 },
    { name: "Rodri", pos: "VOL", rating: 93 },
    { name: "Kevin De Bruyne", pos: "MEI", alt: ["MC"], rating: 94 },
    { name: "Rúben Dias", pos: "ZAG", rating: 90 },
    { name: "İlkay Gündoğan", pos: "MC", alt: ["VOL"], rating: 82 },
    { name: "Bernardo Silva", pos: "MEI", alt: ["MC", "PD"], rating: 82 },
    { name: "Ederson", pos: "GOL", rating: 82 },
    { name: "Kyle Walker", pos: "LD", alt: ["MD"], rating: 81 },
    { name: "Riyad Mahrez", pos: "PD", alt: ["MD"], rating: 81 },
    { name: "Manuel Akanji", pos: "ZAG", rating: 80 },
    { name: "John Stones", pos: "ZAG", rating: 80 },
    { name: "Phil Foden", pos: "PD", alt: ["MD"], rating: 80 },
    { name: "Jack Grealish", pos: "PE", alt: ["ME"], rating: 80 },
    { name: "Aymeric Laporte", pos: "ZAG", rating: 79 },
    { name: "Julián Álvarez", pos: "ATA", rating: 79 },
    { name: "Nathan Aké", pos: "LE", alt: ["ME"], rating: 79 },
    { name: "Kalvin Phillips", pos: "VOL", alt: ["MC"], rating: 77 },
    { name: "Stefan Ortega", pos: "GOL", rating: 75 },
  ],
  "rm-2021": [
    { name: "Thibaut Courtois", pos: "GOL", rating: 91 },
    { name: "Karim Benzema", pos: "ATA", rating: 96 },
    { name: "Toni Kroos", pos: "MC", alt: ["VOL"], rating: 88 },
    { name: "Rodrygo", pos: "PD", alt: ["MD", "ATA"], rating: 87 },
    { name: "Vinícius Júnior", pos: "PE", alt: ["ME", "ATA"], rating: 85 },
    { name: "Luka Modrić", pos: "MC", alt: ["MEI"], rating: 89 },
    { name: "Éder Militão", pos: "ZAG", alt: ["LD"], rating: 82 },
    { name: "Marcelo", pos: "LE", alt: ["ME", "PE"], rating: 81 },
    { name: "Casemiro", pos: "VOL", alt: ["MC"], rating: 81 },
    { name: "Federico Valverde", pos: "MC", alt: ["VOL", "LD"], rating: 81 },
    { name: "Dani Carvajal", pos: "LD", alt: ["MD"], rating: 79 },
    { name: "David Alaba", pos: "ZAG", alt: ["LE"], rating: 79 },
    { name: "Eduardo Camavinga", pos: "MC", alt: ["VOL", "MEI"], rating: 79 },
    { name: "Marco Asensio", pos: "PD", alt: ["MD"], rating: 78 },
    { name: "Nacho Fernández", pos: "ZAG", rating: 77 },
    { name: "Ferland Mendy", pos: "LE", alt: ["ME"], rating: 77 },
    { name: "Dani Ceballos", pos: "MC", alt: ["VOL"], rating: 76 },
    { name: "Andriy Lunin", pos: "GOL", rating: 75 },
  ],
  "che-2020": [
    { name: "Thiago Silva", pos: "ZAG", rating: 90 },
    { name: "N'Golo Kanté", pos: "VOL", alt: ["MC"], rating: 91 },
    { name: "Jorginho", pos: "MC", alt: ["VOL", "MEI"], rating: 83 },
    { name: "Kai Havertz", pos: "MEI", alt: ["ATA"], rating: 83 },
    { name: "Antonio Rüdiger", pos: "ZAG", rating: 82 },
    { name: "Hakim Ziyech", pos: "PD", alt: ["MD"], rating: 82 },
    { name: "Christian Pulisic", pos: "PE", alt: ["ME"], rating: 82 },
    { name: "Andreas Christensen", pos: "ZAG", rating: 80 },
    { name: "Reece James", pos: "LD", alt: ["MD"], rating: 80 },
    { name: "Mason Mount", pos: "MEI", alt: ["MC"], rating: 80 },
    { name: "Timo Werner", pos: "ATA", rating: 80 },
    { name: "Mateo Kovačić", pos: "MC", alt: ["VOL"], rating: 79 },
    { name: "Olivier Giroud", pos: "ATA", rating: 79 },
    { name: "Édouard Mendy", pos: "GOL", rating: 79 },
    { name: "César Azpilicueta", pos: "LD", alt: ["MD"], rating: 78 },
    { name: "Ben Chilwell", pos: "LE", alt: ["ME"], rating: 78 },
    { name: "Kepa Arrizabalaga", pos: "GOL", rating: 77 },
    { name: "Tammy Abraham", pos: "ATA", rating: 77 },
  ],
  "bay-2019": [
    { name: "Robert Lewandowski", pos: "ATA", rating: 96 },
    { name: "Manuel Neuer", pos: "GOL", rating: 92 },
    { name: "Thomas Müller", pos: "MEI", alt: ["ATA"], rating: 91 },
    { name: "Joshua Kimmich", pos: "LD", alt: ["MD"], rating: 90 },
    { name: "Leon Goretzka", pos: "MC", alt: ["VOL"], rating: 83 },
    { name: "Kingsley Coman", pos: "PE", alt: ["ME"], rating: 83 },
    { name: "Alphonso Davies", pos: "LE", alt: ["ME"], rating: 82 },
    { name: "Thiago Alcântara", pos: "MC", alt: ["VOL", "MEI"], rating: 82 },
    { name: "Niklas Süle", pos: "ZAG", rating: 81 },
    { name: "Ivan Perišić", pos: "PE", alt: ["ME"], rating: 81 },
    { name: "Serge Gnabry", pos: "PD", alt: ["MD"], rating: 81 },
    { name: "Philippe Coutinho", pos: "MEI", alt: ["MC"], rating: 80 },
    { name: "Jérôme Boateng", pos: "ZAG", rating: 80 },
    { name: "David Alaba", pos: "ZAG", alt: ["LE"], rating: 79 },
    { name: "Benjamin Pavard", pos: "LD", alt: ["MD"], rating: 79 },
    { name: "Corentin Tolisso", pos: "MC", alt: ["MEI"], rating: 78 },
    { name: "Sven Ulreich", pos: "GOL", rating: 77 },
    { name: "Lucas Hernández", pos: "LE", alt: ["ZAG"], rating: 77 },
  ],
  "liv-2018": [
    { name: "Virgil van Dijk", pos: "ZAG", rating: 94 },
    { name: "Mohamed Salah", pos: "PD", alt: ["MD"], rating: 94 },
    { name: "Alisson Becker", pos: "GOL", rating: 90 },
    { name: "Sadio Mané", pos: "PE", alt: ["ME"], rating: 91 },
    { name: "Trent Alexander-Arnold", pos: "LD", alt: ["MD"], rating: 90 },
    { name: "Roberto Firmino", pos: "ATA", rating: 84 },
    { name: "Andrew Robertson", pos: "LE", alt: ["ME"], rating: 82 },
    { name: "Joël Matip", pos: "ZAG", rating: 82 },
    { name: "Jordan Henderson", pos: "MC", alt: ["VOL", "MEI"], rating: 82 },
    { name: "Fabinho", pos: "VOL", alt: ["MC"], rating: 81 },
    { name: "Joe Gomez", pos: "ZAG", rating: 80 },
    { name: "James Milner", pos: "MC", alt: ["MEI"], rating: 80 },
    { name: "Georginio Wijnaldum", pos: "MC", alt: ["VOL"], rating: 80 },
    { name: "Divock Origi", pos: "ATA", rating: 79 },
    { name: "Simon Mignolet", pos: "GOL", rating: 78 },
    { name: "Naby Keïta", pos: "MC", alt: ["VOL"], rating: 78 },
    { name: "Xherdan Shaqiri", pos: "PD", alt: ["MD"], rating: 78 },
    { name: "Daniel Sturridge", pos: "ATA", rating: 78 },
  ],
  "rm-2017": [
    { name: "Cristiano Ronaldo", pos: "PE", alt: ["ME", "ATA"], rating: 95 },
    { name: "Gareth Bale", pos: "PD", alt: ["MD"], rating: 90 },
    { name: "Sergio Ramos", pos: "ZAG", alt: ["LD"], rating: 87 },
    { name: "Keylor Navas", pos: "GOL", rating: 85 },
    { name: "Casemiro", pos: "VOL", alt: ["MC"], rating: 85 },
    { name: "Raphaël Varane", pos: "ZAG", rating: 84 },
    { name: "Marcelo", pos: "LE", alt: ["ME"], rating: 83 },
    { name: "Toni Kroos", pos: "MC", alt: ["VOL"], rating: 82 },
    { name: "Luka Modrić", pos: "MC", alt: ["MEI"], rating: 94 },
    { name: "Karim Benzema", pos: "ATA", rating: 82 },
    { name: "Dani Carvajal", pos: "LD", alt: ["MD"], rating: 81 },
    { name: "Isco", pos: "MEI", alt: ["MC", "PD"], rating: 81 },
    { name: "Marco Asensio", pos: "MEI", alt: ["MC", "PD"], rating: 79 },
    { name: "Kiko Casilla", pos: "GOL", rating: 78 },
    { name: "Nacho Fernández", pos: "ZAG", rating: 78 },
    { name: "Lucas Vázquez", pos: "PD", alt: ["MD"], rating: 78 },
    { name: "Mateo Kovačić", pos: "MC", alt: ["VOL"], rating: 78 },
    { name: "Achraf Hakimi", pos: "LD", alt: ["MD"], rating: 77 },
  ],
  "rm-2016": [
    { name: "Cristiano Ronaldo", pos: "PE", alt: ["ME", "ATA"], rating: 99 },
    { name: "Sergio Ramos", pos: "ZAG", alt: ["LD"], rating: 88 },
    { name: "Gareth Bale", pos: "PD", alt: ["MD"], rating: 88 },
    { name: "Keylor Navas", pos: "GOL", rating: 85 },
    { name: "Raphaël Varane", pos: "ZAG", rating: 85 },
    { name: "Casemiro", pos: "VOL", alt: ["MC"], rating: 88 },
    { name: "Toni Kroos", pos: "MC", alt: ["VOL"], rating: 92 },
    { name: "Karim Benzema", pos: "ATA", rating: 83 },
    { name: "Marcelo", pos: "LE", alt: ["ME"], rating: 82 },
    { name: "Luka Modrić", pos: "MC", alt: ["MEI"], rating: 82 },
    { name: "Dani Carvajal", pos: "LD", alt: ["MD"], rating: 81 },
    { name: "Isco", pos: "MEI", alt: ["MC", "PD"], rating: 80 },
    { name: "Marco Asensio", pos: "MEI", alt: ["MC", "PD"], rating: 80 },
    { name: "Nacho Fernández", pos: "ZAG", rating: 79 },
    { name: "Danilo", pos: "LD", alt: ["MD"], rating: 78 },
    { name: "Mateo Kovačić", pos: "MC", alt: ["VOL"], rating: 78 },
    { name: "Álvaro Morata", pos: "ATA", rating: 78 },
    { name: "Kiko Casilla", pos: "GOL", rating: 77 },
  ],
  "rm-2015": [
    { name: "Cristiano Ronaldo", pos: "PE", alt: ["ME", "ATA"], rating: 92 },
    { name: "Sergio Ramos", pos: "ZAG", alt: ["LD"], rating: 87 },
    { name: "Gareth Bale", pos: "PD", alt: ["MD"], rating: 84 },
    { name: "Keylor Navas", pos: "GOL", rating: 83 },
    { name: "Luka Modrić", pos: "MC", alt: ["MEI"], rating: 83 },
    { name: "Casemiro", pos: "VOL", alt: ["MC"], rating: 82 },
    { name: "Karim Benzema", pos: "ATA", rating: 82 },
    { name: "Marcelo", pos: "LE", alt: ["ME"], rating: 81 },
    { name: "Toni Kroos", pos: "MC", alt: ["VOL"], rating: 81 },
    { name: "Pepe", pos: "ZAG", rating: 80 },
    { name: "Dani Carvajal", pos: "LD", alt: ["MD"], rating: 80 },
    { name: "Nacho Fernández", pos: "ZAG", rating: 79 },
    { name: "James Rodríguez", pos: "MEI", alt: ["MC", "PD"], rating: 79 },
    { name: "Isco", pos: "MEI", alt: ["MC", "PD"], rating: 79 },
    { name: "Kiko Casilla", pos: "GOL", rating: 78 },
    { name: "Danilo", pos: "LD", alt: ["MD"], rating: 78 },
    { name: "Lucas Vázquez", pos: "PD", alt: ["MD"], rating: 76 },
    { name: "Jesé", pos: "ATA", rating: 76 },
  ],
  "bar-2014": [
    { name: "Lionel Messi", pos: "PD", alt: ["MD", "MEI", "ATA"], rating: 99 },
    { name: "Neymar", pos: "PE", alt: ["ME", "MEI", "ATA"], rating: 92 },
    { name: "Luis Suárez", pos: "ATA", rating: 91 },
    { name: "Sergio Busquets", pos: "VOL", alt: ["MC"], rating: 89 },
    { name: "Gerard Piqué", pos: "ZAG", rating: 84 },
    { name: "Andrés Iniesta", pos: "MC", alt: ["MEI"], rating: 92 },
    { name: "Xavi", pos: "MC", alt: ["MEI"], rating: 83 },
    { name: "Marc-André ter Stegen", pos: "GOL", rating: 82 },
    { name: "Javier Mascherano", pos: "VOL", alt: ["ZAG"], rating: 82 },
    { name: "Ivan Rakitić", pos: "MC", alt: ["VOL", "MEI"], rating: 81 },
    { name: "Dani Alves", pos: "LD", alt: ["MD"], rating: 80 },
    { name: "Pedro", pos: "PD", alt: ["MD"], rating: 79 },
    { name: "Claudio Bravo", pos: "GOL", rating: 79 },
    { name: "Jordi Alba", pos: "LE", alt: ["ME"], rating: 78 },
    { name: "Rafinha", pos: "MEI", alt: ["MC"], rating: 78 },
    { name: "Marc Bartra", pos: "ZAG", rating: 78 },
    { name: "Jérémy Mathieu", pos: "ZAG", rating: 75 },
    { name: "Adriano", pos: "LE", alt: ["ME"], rating: 75 },
  ],
  "rm-2013": [
    { name: "Sergio Ramos", pos: "ZAG", alt: ["LD"], rating: 92 },
    { name: "Cristiano Ronaldo", pos: "PE", alt: ["ME", "ATA"], rating: 93 },
    { name: "Raphaël Varane", pos: "ZAG", rating: 82 },
    { name: "Luka Modrić", pos: "MC", alt: ["MEI"], rating: 90 },
    { name: "Ángel Di María", pos: "ME", alt: ["PE"], rating: 82 },
    { name: "Gareth Bale", pos: "PD", alt: ["MD"], rating: 82 },
    { name: "Iker Casillas", pos: "GOL", rating: 82 },
    { name: "Pepe", pos: "ZAG", rating: 82 },
    { name: "Karim Benzema", pos: "ATA", rating: 81 },
    { name: "Sami Khedira", pos: "MC", alt: ["VOL"], rating: 80 },
    { name: "Isco", pos: "MEI", alt: ["MC", "PD"], rating: 80 },
    { name: "Dani Carvajal", pos: "LD", alt: ["MD"], rating: 79 },
    { name: "Marcelo", pos: "LE", alt: ["ME", "PE"], rating: 79 },
    { name: "Álvaro Arbeloa", pos: "LD", alt: ["MD"], rating: 79 },
    { name: "Fábio Coentrão", pos: "LE", alt: ["ME"], rating: 79 },
    { name: "Diego López", pos: "GOL", rating: 77 },
    { name: "Álvaro Morata", pos: "ATA", rating: 77 },
    { name: "Asier Illarramendi", pos: "VOL", alt: ["MC"], rating: 75 },
  ],
  "bay-2012": [
    { name: "Franck Ribéry", pos: "PE", alt: ["ME"], rating: 94 },
    { name: "Arjen Robben", pos: "PD", alt: ["MD"], rating: 93 },
    { name: "Manuel Neuer", pos: "GOL", rating: 89 },
    { name: "Philipp Lahm", pos: "LD", alt: ["MD"], rating: 88 },
    { name: "Jérôme Boateng", pos: "ZAG", rating: 87 },
    { name: "Thomas Müller", pos: "MEI", alt: ["MC", "ATA"], rating: 87 },
    { name: "Dante", pos: "ZAG", rating: 85 },
    { name: "Bastian Schweinsteiger", pos: "MC", alt: ["VOL"], rating: 85 },
    { name: "David Alaba", pos: "LE", rating: 84 },
    { name: "Mario Mandžukić", pos: "ATA", rating: 84 },
    { name: "Daniel Van Buyten", pos: "ZAG", rating: 83 },
    { name: "Mario Gómez", pos: "ATA", rating: 82 },
    { name: "Luiz Gustavo", pos: "VOL", alt: ["MC"], rating: 82 },
    { name: "Xherdan Shaqiri", pos: "PD", alt: ["MD"], rating: 82 },
    { name: "Javi Martínez", pos: "VOL", alt: ["MC"], rating: 81 },
    { name: "Anatoliy Tymoshchuk", pos: "VOL", alt: ["MC"], rating: 80 },
    { name: "Claudio Pizarro", pos: "ATA", rating: 78 },
    { name: "Tom Starke", pos: "GOL", rating: 78 },
  ],
  "che-2011": [
    { name: "Petr Čech", pos: "GOL", rating: 90 },
    { name: "Frank Lampard", pos: "MC", alt: ["VOL", "MEI"], rating: 85 },
    { name: "Didier Drogba", pos: "ATA", rating: 85 },
    { name: "Fernando Torres", pos: "ATA", rating: 84 },
    { name: "Ashley Cole", pos: "LE", alt: ["ME"], rating: 83 },
    { name: "David Luiz", pos: "ZAG", rating: 82 },
    { name: "Michael Essien", pos: "VOL", alt: ["MC"], rating: 82 },
    { name: "Gary Cahill", pos: "ZAG", rating: 81 },
    { name: "Juan Mata", pos: "MEI", alt: ["MC"], rating: 81 },
    { name: "John Obi Mikel", pos: "VOL", alt: ["MC"], rating: 79 },
    { name: "Ryan Bertrand", pos: "PE", alt: ["ME"], rating: 79 },
    { name: "Oriol Romeu", pos: "VOL", alt: ["MC"], rating: 78 },
    { name: "Salomon Kalou", pos: "PD", alt: ["MD"], rating: 78 },
    { name: "Ross Turnbull", pos: "GOL", rating: 77 },
    { name: "José Bosingwa", pos: "LD", alt: ["MD"], rating: 77 },
    { name: "Paulo Ferreira", pos: "LD", alt: ["MD"], rating: 77 },
    { name: "Daniel Sturridge", pos: "ATA", rating: 77 },
    { name: "Florent Malouda", pos: "PE", alt: ["ME"], rating: 76 },
  ],
  "bar-2010": [
    { name: "Lionel Messi", pos: "PD", alt: ["MD", "MEI", "ATA"], rating: 95 },
    { name: "Xavi", pos: "MC", alt: ["MEI"], rating: 91 },
    { name: "Andrés Iniesta", pos: "MC", alt: ["MEI"], rating: 92 },
    { name: "Sergio Busquets", pos: "VOL", alt: ["MC"], rating: 86 },
    { name: "Víctor Valdés", pos: "GOL", rating: 85 },
    { name: "Carles Puyol", pos: "ZAG", alt: ["LD"], rating: 85 },
    { name: "David Villa", pos: "ATA", rating: 85 },
    { name: "Dani Alves", pos: "LD", alt: ["MD"], rating: 83 },
    { name: "Javier Mascherano", pos: "VOL", alt: ["ZAG"], rating: 82 },
    { name: "Pedro", pos: "PD", alt: ["MD"], rating: 82 },
    { name: "Thiago Alcântara", pos: "MC", alt: ["VOL", "MEI"], rating: 82 },
    { name: "Gerard Piqué", pos: "ZAG", rating: 80 },
    { name: "Adriano", pos: "LE", alt: ["ME"], rating: 79 },
    { name: "Eric Abidal", pos: "LE", alt: ["ME"], rating: 79 },
    { name: "Seydou Keita", pos: "MC", alt: ["VOL"], rating: 77 },
    { name: "Bojan Krkić", pos: "ATA", rating: 77 },
    { name: "Ibrahim Afellay", pos: "PE", alt: ["ME"], rating: 75 },
    { name: "Oier Olazábal", pos: "GOL", rating: 75 },
  ],
  "int-2009": [
    { name: "Wesley Sneijder", pos: "MEI", alt: ["MC"], rating: 93 },
    { name: "Júlio César", pos: "GOL", rating: 88 },
    { name: "Samuel Eto'o", pos: "PD", alt: ["MD"], rating: 87 },
    { name: "Lúcio", pos: "ZAG", rating: 86 },
    { name: "Javier Zanetti", pos: "VOL", alt: ["MC"], rating: 86 },
    { name: "Maicon", pos: "LD", alt: ["MD"], rating: 85 },
    { name: "Diego Milito", pos: "ATA", rating: 85 },
    { name: "Marco Materazzi", pos: "ZAG", rating: 83 },
    { name: "Esteban Cambiasso", pos: "VOL", alt: ["MC"], rating: 82 },
    { name: "Walter Samuel", pos: "ZAG", rating: 79 },
    { name: "Dejan Stanković", pos: "MC", alt: ["VOL"], rating: 79 },
    { name: "Mario Balotelli", pos: "ATA", rating: 79 },
    { name: "Iván Córdoba", pos: "ZAG", rating: 79 },
    { name: "Cristian Chivu", pos: "LE", alt: ["ME"], rating: 78 },
    { name: "Goran Pandev", pos: "PE", alt: ["ME"], rating: 78 },
    { name: "Sulley Muntari", pos: "MC", alt: ["VOL"], rating: 77 },
    { name: "McDonald Mariga", pos: "MC", alt: ["VOL"], rating: 75 },
    { name: "Francesco Toldo", pos: "GOL", rating: 75 },
  ],
  "bar-2008": [
    { name: "Lionel Messi", pos: "PD", alt: ["MD", "MEI", "ATA"], rating: 93 },
    { name: "Thierry Henry", pos: "PE", alt: ["ME", "ATA"], rating: 87 },
    { name: "Samuel Eto'o", pos: "ATA", rating: 87 },
    { name: "Andrés Iniesta", pos: "MC", alt: ["MEI"], rating: 84 },
    { name: "Víctor Valdés", pos: "GOL", rating: 83 },
    { name: "Yaya Touré", pos: "VOL", alt: ["MC"], rating: 83 },
    { name: "Xavi", pos: "MC", alt: ["MEI"], rating: 91 },
    { name: "Sergio Busquets", pos: "VOL", alt: ["MC"], rating: 82 },
    { name: "Carles Puyol", pos: "LD", alt: ["ZAG"], rating: 82 },
    { name: "Gerard Piqué", pos: "ZAG", rating: 80 },
    { name: "Pedro", pos: "PD", alt: ["MD"], rating: 80 },
    { name: "Seydou Keita", pos: "MC", alt: ["VOL"], rating: 79 },
    { name: "Marc Muniesa", pos: "ZAG", rating: 79 },
    { name: "José Manuel Pinto", pos: "GOL", rating: 77 },
    { name: "Martín Cáceres", pos: "ZAG", rating: 77 },
    { name: "Bojan Krkić", pos: "ATA", rating: 76 },
    { name: "Sylvinho", pos: "LE", alt: ["ME"], rating: 75 },
    { name: "Eiður Guðjohnsen", pos: "ATA", rating: 75 },
  ],
  "mun-2007": [
    { name: "Cristiano Ronaldo", pos: "PE", alt: ["ME", "ATA"], rating: 88 },
    { name: "Edwin van der Sar", pos: "GOL", rating: 86 },
    { name: "Rio Ferdinand", pos: "ZAG", rating: 86 },
    { name: "Wayne Rooney", pos: "ATA", alt: ["MEI"], rating: 86 },
    { name: "Carlos Tévez", pos: "ATA", rating: 85 },
    { name: "Nemanja Vidić", pos: "ZAG", rating: 84 },
    { name: "Paul Scholes", pos: "MC", alt: ["MEI"], rating: 84 },
    { name: "Ryan Giggs", pos: "MEI", alt: ["MC", "ATA"], rating: 83 },
    { name: "Patrice Evra", pos: "LE", alt: ["ME"], rating: 82 },
    { name: "Nani", pos: "PD", alt: ["MD"], rating: 82 },
    { name: "Michael Carrick", pos: "MC", alt: ["VOL"], rating: 80 },
    { name: "Owen Hargreaves", pos: "MD", alt: ["PD"], rating: 79 },
    { name: "Anderson", pos: "MC", alt: ["VOL"], rating: 79 },
    { name: "Wes Brown", pos: "LD", alt: ["MD"], rating: 79 },
    { name: "Darren Fletcher", pos: "MC", alt: ["VOL"], rating: 78 },
    { name: "John O'Shea", pos: "LD", alt: ["MD"], rating: 76 },
    { name: "Tomasz Kuszczak", pos: "GOL", rating: 75 },
    { name: "Mikaël Silvestre", pos: "ZAG", rating: 75 },
  ],
  "mil-2006": [
    { name: "Paolo Maldini", pos: "ZAG", alt: ["LE"], rating: 91 },
    { name: "Kaká", pos: "MEI", alt: ["MC", "ATA"], rating: 93 },
    { name: "Alessandro Nesta", pos: "ZAG", rating: 87 },
    { name: "Andrea Pirlo", pos: "MEI", alt: ["MC", "VOL"], rating: 87 },
    { name: "Gennaro Gattuso", pos: "VOL", alt: ["MC"], rating: 85 },
    { name: "Dida", pos: "GOL", rating: 84 },
    { name: "Clarence Seedorf", pos: "MC", alt: ["MEI"], rating: 83 },
    { name: "Massimo Ambrosini", pos: "VOL", alt: ["MC"], rating: 82 },
    { name: "Filippo Inzaghi", pos: "ATA", rating: 82 },
    { name: "Massimo Oddo", pos: "LD", alt: ["MD"], rating: 79 },
    { name: "Daniele Bonera", pos: "ZAG", rating: 78 },
    { name: "Marek Jankulovski", pos: "LE", alt: ["ME"], rating: 76 },
    { name: "Alberto Gilardino", pos: "ATA", rating: 76 },
    { name: "Kakha Kaladze", pos: "ZAG", rating: 76 },
    { name: "Zeljko Kalac", pos: "GOL", rating: 75 },
    { name: "Serginho", pos: "PE", alt: ["ME"], rating: 75 },
    { name: "Yoann Gourcuff", pos: "MEI", alt: ["MC"], rating: 75 },
  ],
  "bar-2005": [
    { name: "Ronaldinho", pos: "MEI", alt: ["PE"], rating: 96 },
    { name: "Carles Puyol", pos: "ZAG", alt: ["LD"], rating: 86 },
    { name: "Deco", pos: "MEI", alt: ["MC"], rating: 85 },
    { name: "Samuel Eto'o", pos: "ATA", rating: 85 },
    { name: "Xavi", pos: "MC", alt: ["MEI"], rating: 83 },
    { name: "Víctor Valdés", pos: "GOL", rating: 82 },
    { name: "Andrés Iniesta", pos: "MC", alt: ["MEI"], rating: 82 },
    { name: "Lionel Messi", pos: "PD", alt: ["MD", "MEI"], rating: 84 },
    { name: "Ludovic Giuly", pos: "PD", alt: ["MD"], rating: 81 },
    { name: "Henrik Larsson", pos: "ATA", rating: 79 },
    { name: "Rafael Márquez", pos: "ZAG", rating: 78 },
    { name: "Juliano Belletti", pos: "LD", alt: ["MD"], rating: 78 },
    { name: "Oleguer", pos: "LD", alt: ["MD"], rating: 77 },
    { name: "Mark van Bommel", pos: "MC", alt: ["VOL"], rating: 77 },
    { name: "Edmílson", pos: "VOL", alt: ["MC"], rating: 77 },
    { name: "Sylvinho", pos: "LE", alt: ["ME"], rating: 76 },
    { name: "Giovanni van Bronckhorst", pos: "LE", alt: ["ME"], rating: 75 },
    { name: "Albert Jorquera", pos: "GOL", rating: 75 },
  ],
  "liv-2004": [
    { name: "Steven Gerrard", pos: "MC", alt: ["VOL"], rating: 87 },
    { name: "Xabi Alonso", pos: "MC", alt: ["VOL"], rating: 82 },
    { name: "Jerzy Dudek", pos: "GOL", rating: 81 },
    { name: "Djibril Cissé", pos: "ATA", rating: 81 },
    { name: "Vladimír Šmicer", pos: "MEI", alt: ["MC"], rating: 80 },
    { name: "Jamie Carragher", pos: "ZAG", rating: 79 },
    { name: "Luis García", pos: "PD", alt: ["MD"], rating: 79 },
    { name: "Djimi Traoré", pos: "ZAG", rating: 79 },
    { name: "Harry Kewell", pos: "ME", alt: ["PE"], rating: 79 },
    { name: "Milan Baroš", pos: "ATA", rating: 79 },
    { name: "Sami Hyypiä", pos: "ZAG", rating: 78 },
    { name: "Dietmar Hamann", pos: "VOL", alt: ["MC"], rating: 78 },
    { name: "Igor Bišćan", pos: "VOL", alt: ["MC"], rating: 78 },
    { name: "Antonio Núñez", pos: "MD", alt: ["PD"], rating: 77 },
    { name: "Steve Finnan", pos: "LD", alt: ["MD"], rating: 76 },
    { name: "John Arne Riise", pos: "LE", alt: ["ME"], rating: 75 },
    { name: "Stephen Warnock", pos: "LE", alt: ["ME"], rating: 75 },
    { name: "Scott Carson", pos: "GOL", rating: 75 },
  ],
  "por-2003": [
    { name: "Deco", pos: "MEI", alt: ["MC"], rating: 88 },
    { name: "Ricardo Carvalho", pos: "ZAG", rating: 82 },
    { name: "Jorge Costa", pos: "ZAG", rating: 78 },
    { name: "Vítor Baía", pos: "GOL", rating: 77 },
    { name: "Ricardo Costa", pos: "ZAG", rating: 77 },
    { name: "Edgaras Jankauskas", pos: "ATA", rating: 77 },
    { name: "Costinha", pos: "VOL", alt: ["MC"], rating: 77 },
    { name: "Maniche", pos: "MC", alt: ["VOL"], rating: 77 },
    { name: "Pedro Mendes", pos: "MC", alt: ["VOL"], rating: 76 },
    { name: "José Bosingwa", pos: "LD", alt: ["MD"], rating: 76 },
    { name: "Pedro Emanuel", pos: "ZAG", rating: 75 },
    { name: "Dmitri Alenichev", pos: "MEI", alt: ["MC"], rating: 75 },
    { name: "Carlos Alberto", pos: "ATA", rating: 75 },
    { name: "Benni McCarthy", pos: "ATA", rating: 75 },
    { name: "Paulo Ferreira", pos: "LD", alt: ["MD"], rating: 75 },
    { name: "Derlei", pos: "ATA", rating: 75 },
    { name: "Nuno Valente", pos: "LE", alt: ["ME"], rating: 75 },
    { name: "Nuno Espírito Santo", pos: "GOL", rating: 75 },
  ],
  "mil-2002": [
    { name: "Paolo Maldini", pos: "ZAG", alt: ["LE"], rating: 91 },
    { name: "Dida", pos: "GOL", rating: 90 },
    { name: "Andrea Pirlo", pos: "MEI", alt: ["MC"], rating: 90 },
    { name: "Alessandro Nesta", pos: "ZAG", rating: 88 },
    { name: "Rui Costa", pos: "MEI", alt: ["MC", "ATA"], rating: 87 },
    { name: "Rivaldo", pos: "MEI", alt: ["ATA", "PD"], rating: 86 },
    { name: "Andriy Shevchenko", pos: "ATA", rating: 92 },
    { name: "Clarence Seedorf", pos: "MC", alt: ["MEI"], rating: 83 },
    { name: "Filippo Inzaghi", pos: "ATA", rating: 83 },
    { name: "Gennaro Gattuso", pos: "VOL", alt: ["MC"], rating: 82 },
    { name: "Alessandro Costacurta", pos: "ZAG", rating: 80 },
    { name: "Massimo Ambrosini", pos: "VOL", alt: ["MC"], rating: 80 },
    { name: "Kakha Kaladze", pos: "LE", alt: ["ME"], rating: 77 },
    { name: "Serginho", pos: "PE", alt: ["ME"], rating: 77 },
    { name: "Martin Laursen", pos: "ZAG", rating: 76 },
    { name: "Cristian Brocchi", pos: "MC", alt: ["VOL", "MEI"], rating: 76 },
    { name: "Christian Abbiati", pos: "GOL", rating: 75 },
    { name: "Roque Júnior", pos: "ZAG", rating: 75 },
  ],
  "rm-2001": [
    { name: "Roberto Carlos", pos: "LE", alt: ["PE"], rating: 91 },
    { name: "Zinedine Zidane", pos: "MEI", alt: ["MC"], rating: 94 },
    { name: "Luís Figo", pos: "PD", alt: ["MD", "MEI"], rating: 91 },
    { name: "Fernando Hierro", pos: "ZAG", rating: 82 },
    { name: "Guti", pos: "MEI", alt: ["MC"], rating: 82 },
    { name: "Fernando Morientes", pos: "ATA", rating: 82 },
    { name: "Raúl", pos: "ATA", alt: ["MEI"], rating: 81 },
    { name: "Iker Casillas", pos: "GOL", rating: 79 },
    { name: "Claude Makélélé", pos: "VOL", alt: ["MC"], rating: 79 },
    { name: "Míchel Salgado", pos: "LD", alt: ["MD"], rating: 78 },
    { name: "Steve McManaman", pos: "ME", alt: ["PE"], rating: 78 },
    { name: "Francisco Pavón", pos: "ZAG", rating: 77 },
    { name: "Iván Helguera", pos: "ZAG", rating: 76 },
    { name: "Flávio Conceição", pos: "VOL", alt: ["MC"], rating: 76 },
    { name: "Santiago Solari", pos: "PE", alt: ["ME"], rating: 76 },
    { name: "Pedro Munitis", pos: "ATA", rating: 76 },
    { name: "César Sánchez", pos: "GOL", rating: 75 },
    { name: "Aitor Karanka", pos: "ZAG", rating: 75 },
  ],
  "bay-2000": [
    { name: "Oliver Kahn", pos: "GOL", rating: 90 },
    { name: "Owen Hargreaves", pos: "MC", alt: ["VOL", "MEI"], rating: 83 },
    { name: "Samuel Kuffour", pos: "ZAG", rating: 82 },
    { name: "Mehmet Scholl", pos: "MEI", alt: ["MC", "ATA"], rating: 82 },
    { name: "Thomas Linke", pos: "ZAG", rating: 81 },
    { name: "Paulo Sérgio", pos: "ATA", rating: 81 },
    { name: "Ciriaco Sforza", pos: "MC", alt: ["VOL"], rating: 80 },
    { name: "Patrik Andersson", pos: "ZAG", rating: 79 },
    { name: "Stefan Effenberg", pos: "MC", alt: ["VOL"], rating: 79 },
    { name: "Giovane Élber", pos: "ATA", rating: 79 },
    { name: "Carsten Jancker", pos: "ATA", rating: 78 },
    { name: "Bixente Lizarazu", pos: "LE", alt: ["ME"], rating: 77 },
    { name: "Hasan Salihamidžić", pos: "MD", alt: ["PD"], rating: 77 },
    { name: "Roque Santa Cruz", pos: "ATA", rating: 77 },
    { name: "Willy Sagnol", pos: "LD", alt: ["MD"], rating: 76 },
    { name: "Alexander Zickler", pos: "ATA", rating: 76 },
    { name: "Bernd Dreher", pos: "GOL", rating: 76 },
    { name: "Michael Tarnat", pos: "LE", alt: ["ME"], rating: 75 },
  ],
  "rm-1999": [
    { name: "Roberto Carlos", pos: "LE", alt: ["PE"], rating: 88 },
    { name: "Fernando Morientes", pos: "ATA", rating: 85 },
    { name: "Fernando Hierro", pos: "ZAG", rating: 83 },
    { name: "Raúl", pos: "ATA", alt: ["MEI"], rating: 83 },
    { name: "Nicolas Anelka", pos: "ATA", rating: 82 },
    { name: "Iván Helguera", pos: "ZAG", rating: 81 },
    { name: "Sávio", pos: "PE", alt: ["ME"], rating: 81 },
    { name: "Iker Casillas", pos: "GOL", rating: 80 },
    { name: "Míchel Salgado", pos: "LD", alt: ["MD"], rating: 79 },
    { name: "Christian Karembeu", pos: "VOL", alt: ["MC"], rating: 79 },
    { name: "Steve McManaman", pos: "ME", alt: ["PE"], rating: 79 },
    { name: "Iván Campo", pos: "ZAG", rating: 79 },
    { name: "Manolo Sanchís", pos: "ZAG", rating: 78 },
    { name: "Geremi", pos: "MD", alt: ["PD"], rating: 78 },
    { name: "Fernando Redondo", pos: "VOL", rating: 77 },
    { name: "Elvir Baljić", pos: "PE", alt: ["ME"], rating: 77 },
    { name: "Bodo Illgner", pos: "GOL", rating: 75 },
  ],
  "mun-1998": [
    { name: "David Beckham", pos: "MD", alt: ["MC", "PD", "MEI"], rating: 90 },
    { name: "Roy Keane", pos: "VOL", alt: ["MC"], rating: 90 },
    { name: "Dwight Yorke", pos: "ATA", rating: 90 },
    { name: "Peter Schmeichel", pos: "GOL", rating: 89 },
    { name: "Ryan Giggs", pos: "ME", alt: ["PE", "MC"], rating: 89 },
    { name: "Andy Cole", pos: "ATA", rating: 87 },
    { name: "Jaap Stam", pos: "ZAG", rating: 86 },
    { name: "Paul Scholes", pos: "MC", alt: ["MEI"], rating: 86 },
    { name: "Denis Irwin", pos: "LE", alt: ["ME"], rating: 85 },
    { name: "Gary Neville", pos: "LD", alt: ["MD"], rating: 83 },
    { name: "Ole Gunnar Solskjær", pos: "ATA", rating: 82 },
    { name: "Teddy Sheringham", pos: "ATA", rating: 81 },
    { name: "Ronny Johnsen", pos: "ZAG", rating: 81 },
    { name: "Nicky Butt", pos: "VOL", alt: ["MC"], rating: 80 },
    { name: "Jesper Blomqvist", pos: "ME", alt: ["PE"], rating: 78 },
    { name: "Phil Neville", pos: "LE", alt: ["ME"], rating: 78 },
    { name: "Wes Brown", pos: "ZAG", rating: 76 },
    { name: "Jonathan Greening", pos: "MC", alt: ["VOL"], rating: 75 },
    { name: "David May", pos: "ZAG", rating: 75 },
    { name: "Raimond van der Gouw", pos: "GOL", rating: 75 },
  ],
  "rm-1997": [
    { name: "Fernando Redondo", pos: "VOL", rating: 90 },
    { name: "Roberto Carlos", pos: "LE", alt: ["PE"], rating: 90 },
    { name: "Raúl", pos: "ATA", alt: ["MEI"], rating: 90 },
    { name: "Fernando Hierro", pos: "ZAG", rating: 90 },
    { name: "Predrag Mijatović", pos: "ATA", rating: 89 },
    { name: "Clarence Seedorf", pos: "MC", alt: ["MEI"], rating: 86 },
    { name: "Davor Šuker", pos: "ATA", rating: 86 },
    { name: "Christian Panucci", pos: "LD", alt: ["MD"], rating: 84 },
    { name: "Christian Karembeu", pos: "MC", alt: ["VOL"], rating: 83 },
    { name: "Manolo Sanchís", pos: "ZAG", rating: 81 },
    { name: "Fernando Morientes", pos: "ATA", rating: 81 },
    { name: "Bodo Illgner", pos: "GOL", rating: 81 },
    { name: "José Amavisca", pos: "ME", alt: ["PE"], rating: 80 },
    { name: "Sávio", pos: "PE", alt: ["ME"], rating: 78 },
    { name: "Jaime Sánchez", pos: "VOL", alt: ["MC"], rating: 77 },
    { name: "Víctor Sánchez", pos: "MD", alt: ["PD"], rating: 76 },
    { name: "Fernando Sanz", pos: "ZAG", rating: 75 },
    { name: "Santiago Cañizares", pos: "GOL", rating: 75 },
  ],
  "dor-1996": [
    { name: "Matthias Sammer", pos: "ZAG", rating: 91 },
    { name: "Andreas Möller", pos: "MEI", alt: ["MC"], rating: 88 },
    { name: "Karl-Heinz Riedle", pos: "ATA", rating: 87 },
    { name: "Paulo Sousa", pos: "VOL", alt: ["MC"], rating: 86 },
    { name: "Jürgen Kohler", pos: "ZAG", rating: 86 },
    { name: "Paul Lambert", pos: "VOL", alt: ["MC"], rating: 84 },
    { name: "Stéphane Chapuisat", pos: "ATA", rating: 83 },
    { name: "Stefan Reuter", pos: "LD", alt: ["MD"], rating: 82 },
    { name: "Michael Zorc", pos: "MC", alt: ["VOL"], rating: 82 },
    { name: "Lars Ricken", pos: "MEI", alt: ["MC"], rating: 82 },
    { name: "Andreas Heinrich", pos: "LE", alt: ["ME"], rating: 81 },
    { name: "Stefan Klos", pos: "GOL", rating: 80 },
    { name: "Heiko Herrlich", pos: "ATA", rating: 79 },
    { name: "René Tretschok", pos: "LE", alt: ["ME"], rating: 78 },
    { name: "Michael Rummenigge", pos: "ATA", rating: 76 },
    { name: "Stefan Kree", pos: "ZAG", rating: 76 },
    { name: "Dirk Heinen", pos: "GOL", rating: 75 },
  ],
  "juv-1995": [
    { name: "Alessandro Del Piero", pos: "ATA", rating: 88 },
    { name: "Gianluca Vialli", pos: "ATA", rating: 88 },
    { name: "Didier Deschamps", pos: "VOL", alt: ["MC"], rating: 87 },
    { name: "Angelo Peruzzi", pos: "GOL", rating: 87 },
    { name: "Gianluca Pessotto", pos: "LE", alt: ["ME"], rating: 85 },
    { name: "Paolo Sousa", pos: "VOL", alt: ["MC"], rating: 85 },
    { name: "Ciro Ferrara", pos: "ZAG", rating: 84 },
    { name: "Vladimir Jugović", pos: "MC", alt: ["VOL"], rating: 84 },
    { name: "Antonio Conte", pos: "MC", alt: ["VOL"], rating: 83 },
    { name: "Paolo Montero", pos: "ZAG", rating: 82 },
    { name: "Alen Bokšić", pos: "ATA", rating: 82 },
    { name: "Massimo Carrera", pos: "ZAG", rating: 82 },
    { name: "Moreno Torricelli", pos: "LD", alt: ["MD"], rating: 82 },
    { name: "Michele Padovano", pos: "ATA", rating: 80 },
    { name: "Angelo Di Livio", pos: "MD", alt: ["PD"], rating: 79 },
    { name: "Michelangelo Rampulla", pos: "GOL", rating: 75 },
  ],
  "aja-1994": [
    { name: "Frank Rijkaard", pos: "VOL", alt: ["ZAG"], rating: 85 },
    { name: "Edwin van der Sar", pos: "GOL", rating: 84 },
    { name: "Clarence Seedorf", pos: "MC", alt: ["MEI"], rating: 84 },
    { name: "Edgar Davids", pos: "VOL", alt: ["MC"], rating: 83 },
    { name: "Nwankwo Kanu", pos: "ATA", rating: 83 },
    { name: "Frank de Boer", pos: "ZAG", rating: 82 },
    { name: "Danny Blind", pos: "ZAG", rating: 82 },
    { name: "Patrick Kluivert", pos: "ATA", rating: 82 },
    { name: "Kiki Musampa", pos: "MEI", alt: ["MC"], rating: 81 },
    { name: "Jari Litmanen", pos: "MEI", alt: ["ATA"], rating: 79 },
    { name: "Fred Grim", pos: "GOL", rating: 79 },
    { name: "Ronald de Boer", pos: "MEI", alt: ["MC"], rating: 77 },
    { name: "Winston Bogarde", pos: "LE", alt: ["ME"], rating: 77 },
    { name: "Marc Overmars", pos: "PE", alt: ["ME"], rating: 76 },
    { name: "Michael Reiziger", pos: "LD", alt: ["MD"], rating: 76 },
    { name: "Finidi George", pos: "PD", alt: ["MD"], rating: 75 },
  ],
  "mil-1993": [
    { name: "Franco Baresi", pos: "ZAG", rating: 89 },
    { name: "Paolo Maldini", pos: "ZAG", alt: ["LE"], rating: 89 },
    { name: "Dejan Savićević", pos: "MEI", alt: ["PD"], rating: 89 },
    { name: "Marcel Desailly", pos: "VOL", alt: ["ZAG"], rating: 87 },
    { name: "Demetrio Albertini", pos: "MC", alt: ["VOL"], rating: 85 },
    { name: "Mauro Tassotti", pos: "LD", alt: ["MD"], rating: 84 },
    { name: "Alessandro Costacurta", pos: "ZAG", rating: 84 },
    { name: "Zvonimir Boban", pos: "MEI", alt: ["MC"], rating: 83 },
    { name: "Roberto Donadoni", pos: "MD", alt: ["PD"], rating: 83 },
    { name: "Daniele Massaro", pos: "ATA", rating: 82 },
    { name: "Sebastiano Rossi", pos: "GOL", rating: 81 },
    { name: "Christian Panucci", pos: "LD", alt: ["MD"], rating: 81 },
    { name: "Florin Răducioiu", pos: "ATA", rating: 79 },
    { name: "Jean-Pierre Papin", pos: "ATA", rating: 78 },
    { name: "Filippo Galli", pos: "ZAG", rating: 77 },
  ],
  "mar-1992": [
    { name: "Fabien Barthez", pos: "GOL", rating: 88 },
    { name: "Didier Deschamps", pos: "VOL", alt: ["MC"], rating: 87 },
    { name: "Marcel Desailly", pos: "VOL", alt: ["ZAG"], rating: 87 },
    { name: "Basile Boli", pos: "ZAG", rating: 87 },
    { name: "Alen Bokšić", pos: "ATA", rating: 85 },
    { name: "Rudi Völler", pos: "ATA", rating: 84 },
    { name: "Abedi Pelé", pos: "MEI", alt: ["MC", "ATA"], rating: 84 },
    { name: "Jocelyn Angloma", pos: "LD", alt: ["MD"], rating: 83 },
    { name: "Éric Di Meco", pos: "LE", alt: ["ME"], rating: 82 },
    { name: "Jean-Jacques Eydelie", pos: "MC", alt: ["VOL"], rating: 81 },
    { name: "Bernard Casoni", pos: "ZAG", rating: 81 },
    { name: "Franck Sauzée", pos: "MC", alt: ["VOL"], rating: 80 },
    { name: "Jean-Philippe Durand", pos: "VOL", alt: ["MC"], rating: 79 },
    { name: "Manuel Amoros", pos: "LD", alt: ["MD"], rating: 79 },
    { name: "Pascal Olmeta", pos: "GOL", rating: 76 },
  ],
  "bar-1991": [
    { name: "Ronald Koeman", pos: "ZAG", rating: 90 },
    { name: "Hristo Stoichkov", pos: "ATA", rating: 88 },
    { name: "Michael Laudrup", pos: "MEI", alt: ["MC", "ATA"], rating: 88 },
    { name: "Pep Guardiola", pos: "VOL", alt: ["MC"], rating: 85 },
    { name: "José Mari Bakero", pos: "MEI", alt: ["MC", "ATA"], rating: 85 },
    { name: "Andoni Zubizarreta", pos: "GOL", rating: 84 },
    { name: "Txiki Begiristain", pos: "PE", alt: ["ME"], rating: 83 },
    { name: "Eusebio Sacristán", pos: "MC", alt: ["VOL"], rating: 82 },
    { name: "Albert Ferrer", pos: "LD", alt: ["MD"], rating: 82 },
    { name: "Guillermo Amor", pos: "MC", alt: ["VOL"], rating: 82 },
    { name: "Miguel Ángel Nadal", pos: "ZAG", rating: 82 },
    { name: "Julio Salinas", pos: "ATA", rating: 81 },
    { name: "Juan Carlos Rodríguez", pos: "MC", alt: ["VOL"], rating: 78 },
    { name: "Richard Witschge", pos: "MEI", alt: ["MC"], rating: 77 },
    { name: "Carles Busquets", pos: "GOL", rating: 75 },
  ],
  "rsb-1990": [
    { name: "Stevan Stojanović", pos: "GOL", rating: 85 },
    { name: "Darko Pančev", pos: "ATA", rating: 85 },
    { name: "Robert Prosinečki", pos: "MEI", alt: ["MC"], rating: 82 },
    { name: "Goran Vasilijević", pos: "MC", alt: ["VOL"], rating: 81 },
    { name: "Ilija Najdoski", pos: "ZAG", rating: 80 },
    { name: "Duško Radinović", pos: "ZAG", rating: 80 },
    { name: "Vladan Lukić", pos: "ATA", rating: 79 },
    { name: "Dragiša Binić", pos: "PD", alt: ["MD"], rating: 78 },
    { name: "Dejan Savićević", pos: "MEI", alt: ["PD"], rating: 77 },
    { name: "Vladimir Jugović", pos: "MC", alt: ["VOL"], rating: 76 },
    { name: "Miodrag Belodedici", pos: "ZAG", rating: 76 },
    { name: "Refik Šabanadžović", pos: "VOL", alt: ["MC"], rating: 76 },
    { name: "Mile Šestić", pos: "MEI", alt: ["MC"], rating: 76 },
    { name: "Zvonko Milojević", pos: "GOL", rating: 75 },
    { name: "Siniša Mihajlović", pos: "LE", alt: ["ME"], rating: 75 },
  ],
  "mil-1989": [
    { name: "Marco van Basten", pos: "ATA", rating: 95 },
    { name: "Ruud Gullit", pos: "ATA", rating: 89 },
    { name: "Franco Baresi", pos: "ZAG", rating: 89 },
    { name: "Frank Rijkaard", pos: "VOL", alt: ["ZAG"], rating: 88 },
    { name: "Paolo Maldini", pos: "ZAG", alt: ["LE"], rating: 86 },
    { name: "Carlo Ancelotti", pos: "MC", alt: ["VOL", "MEI"], rating: 83 },
    { name: "Roberto Donadoni", pos: "MD", alt: ["PD"], rating: 83 },
    { name: "Alessandro Costacurta", pos: "ZAG", rating: 82 },
    { name: "Mauro Tassotti", pos: "LD", alt: ["MD"], rating: 82 },
    { name: "Angelo Colombo", pos: "MC", alt: ["VOL"], rating: 80 },
    { name: "Daniele Massaro", pos: "ATA", rating: 80 },
    { name: "Andrea Carnevale", pos: "ATA", rating: 78 },
    { name: "Sebastiano Rossi", pos: "GOL", rating: 77 },
    { name: "Filippo Galli", pos: "ZAG", rating: 77 },
    { name: "Alberigo Evani", pos: "ME", alt: ["PE"], rating: 76 },
  ],
  "mil-1988": [
    { name: "Marco van Basten", pos: "ATA", rating: 96 },
    { name: "Ruud Gullit", pos: "ATA", rating: 89 },
    { name: "Franco Baresi", pos: "ZAG", rating: 89 },
    { name: "Frank Rijkaard", pos: "VOL", alt: ["ZAG"], rating: 88 },
    { name: "Paolo Maldini", pos: "ZAG", alt: ["LE"], rating: 85 },
    { name: "Roberto Donadoni", pos: "MD", alt: ["PD"], rating: 83 },
    { name: "Carlo Ancelotti", pos: "MC", alt: ["VOL", "MEI"], rating: 82 },
    { name: "Mauro Tassotti", pos: "LD", alt: ["MD"], rating: 82 },
    { name: "Alessandro Costacurta", pos: "ZAG", rating: 81 },
    { name: "Angelo Colombo", pos: "MC", alt: ["VOL"], rating: 80 },
    { name: "Daniele Massaro", pos: "ATA", rating: 79 },
    { name: "Pietro Paolo Virdis", pos: "ATA", rating: 78 },
    { name: "Filippo Galli", pos: "ZAG", rating: 77 },
    { name: "Giovanni Galli", pos: "GOL", rating: 77 },
    { name: "Alberigo Evani", pos: "ME", alt: ["PE"], rating: 76 },
  ],
  "psv-1987": [
    { name: "Ronald Koeman", pos: "ZAG", rating: 87 },
    { name: "Anton Janssen", pos: "ATA", rating: 82 },
    { name: "Wim Kieft", pos: "ATA", rating: 81 },
    { name: "Hans van Breukelen", pos: "GOL", rating: 80 },
    { name: "Eric Gerets", pos: "LD", alt: ["MD"], rating: 79 },
    { name: "Willy van de Kerkhof", pos: "MC", alt: ["VOL"], rating: 79 },
    { name: "Guus Hiddink", pos: "MEI", alt: ["MC"], rating: 79 },
    { name: "René van de Kerkhof", pos: "MD", alt: ["PD"], rating: 78 },
    { name: "Søren Lerby", pos: "VOL", alt: ["MC"], rating: 77 },
    { name: "Danny Blind", pos: "ZAG", rating: 77 },
    { name: "Heinz Stuy", pos: "GOL", rating: 76 },
    { name: "Gerald Vanenburg", pos: "MD", alt: ["PD"], rating: 76 },
    { name: "Berry van Aerle", pos: "LD", alt: ["MD"], rating: 75 },
    { name: "Adrie van Tiggelen", pos: "LE", alt: ["ME"], rating: 75 },
    { name: "Jan Heintze", pos: "LE", alt: ["ME"], rating: 75 },
  ],
  "por-1986": [
    { name: "Rabah Madjer", pos: "ATA", rating: 91 },
    { name: "Paulo Futre", pos: "PE", alt: ["ME"], rating: 91 },
    { name: "João Pinto", pos: "LD", alt: ["MD"], rating: 86 },
    { name: "Fernando Gomes", pos: "ATA", rating: 86 },
    { name: "Celso", pos: "MC", alt: ["VOL"], rating: 84 },
    { name: "Frasco", pos: "VOL", alt: ["MC"], rating: 84 },
    { name: "Sousa", pos: "MC", alt: ["VOL"], rating: 83 },
    { name: "Eurico", pos: "ZAG", rating: 83 },
    { name: "José Carlos", pos: "ZAG", rating: 82 },
    { name: "Zé Beto", pos: "GOL", rating: 82 },
    { name: "Inácio", pos: "LE", alt: ["ME"], rating: 82 },
    { name: "André", pos: "ATA", rating: 80 },
    { name: "Quim", pos: "MC", alt: ["VOL"], rating: 79 },
    { name: "Juceanu", pos: "ZAG", rating: 78 },
    { name: "Mladenov", pos: "ATA", rating: 77 },
  ],
  "ste-1985": [
    { name: "Marin Radu", pos: "ATA", rating: 87 },
    { name: "Helmuth Duckadam", pos: "GOL", rating: 85 },
    { name: "Ilie Bărbulescu", pos: "LE", alt: ["ME"], rating: 83 },
    { name: "Miodrag Belodedici", pos: "ZAG", rating: 83 },
    { name: "Anton Weissenbacher", pos: "ME", alt: ["PE"], rating: 83 },
    { name: "Victor Pițurcă", pos: "ATA", rating: 81 },
    { name: "Lucian Bălan", pos: "MC", alt: ["VOL"], rating: 80 },
    { name: "Marius Lăcătuș", pos: "PD", alt: ["MD"], rating: 78 },
    { name: "Marin Majearu", pos: "MC", alt: ["VOL"], rating: 76 },
    { name: "Ștefan Iovan", pos: "LD", alt: ["MD"], rating: 76 },
    { name: "Adrian Bumbescu", pos: "ZAG", rating: 76 },
    { name: "Anghel Iordănescu", pos: "ATA", rating: 76 },
    { name: "Constantin Pistol", pos: "ZAG", rating: 76 },
    { name: "Gavril Balint", pos: "ATA", rating: 75 },
    { name: "László Bölöni", pos: "MC", alt: ["VOL"], rating: 75 },
    { name: "Dumitru Stângaciu", pos: "GOL", rating: 75 },
  ],
  "juv-1984": [
    { name: "Michel Platini", pos: "MEI", alt: ["MC"], rating: 95 },
    { name: "Zbigniew Boniek", pos: "ATA", rating: 88 },
    { name: "Gaetano Scirea", pos: "ZAG", rating: 88 },
    { name: "Antonio Cabrini", pos: "LE", alt: ["ME"], rating: 85 },
    { name: "Marco Tardelli", pos: "MC", alt: ["VOL", "MEI"], rating: 85 },
    { name: "Stefano Tacconi", pos: "GOL", rating: 84 },
    { name: "Massimo Bonini", pos: "VOL", alt: ["MC"], rating: 83 },
    { name: "Sergio Brio", pos: "ZAG", rating: 82 },
    { name: "Luciano Favero", pos: "ZAG", rating: 81 },
    { name: "Domenico Penzo", pos: "ATA", rating: 80 },
    { name: "Aldo Serena", pos: "ATA", rating: 80 },
    { name: "Vignola", pos: "MEI", alt: ["MC"], rating: 80 },
    { name: "Massimo Mauro", pos: "MD", alt: ["PD"], rating: 79 },
    { name: "Lanfranco Fortunato", pos: "LD", alt: ["MD"], rating: 77 },
    { name: "Bodini", pos: "GOL", rating: 75 },
  ],
  "liv-1983": [
    { name: "Kenny Dalglish", pos: "ATA", rating: 89 },
    { name: "Graeme Souness", pos: "MC", alt: ["VOL", "MEI"], rating: 88 },
    { name: "Ian Rush", pos: "ATA", rating: 88 },
    { name: "Alan Hansen", pos: "ZAG", rating: 86 },
    { name: "Bruce Grobbelaar", pos: "GOL", rating: 85 },
    { name: "Mark Lawrenson", pos: "ZAG", rating: 84 },
    { name: "Ronnie Whelan", pos: "MC", alt: ["VOL", "MEI"], rating: 83 },
    { name: "Phil Neal", pos: "LD", alt: ["MD"], rating: 82 },
    { name: "Craig Johnston", pos: "MEI", alt: ["MC"], rating: 81 },
    { name: "Sammy Lee", pos: "MC", alt: ["VOL"], rating: 80 },
    { name: "Steve Nicol", pos: "LD", alt: ["MD"], rating: 80 },
    { name: "David Hodgson", pos: "MEI", alt: ["MC"], rating: 78 },
    { name: "Michael Robinson", pos: "ATA", rating: 77 },
    { name: "Bob Bolder", pos: "GOL", rating: 75 },
  ],
  "hsv-1982": [
    { name: "Horst Hrubesch", pos: "ATA", rating: 85 },
    { name: "Jakob Hieronymus", pos: "ZAG", rating: 83 },
    { name: "Ditmar Jakobs", pos: "ZAG", rating: 82 },
    { name: "Felix Magath", pos: "MEI", alt: ["MC"], rating: 82 },
    { name: "Uli Stein", pos: "GOL", rating: 81 },
    { name: "Jimmy Hartwig", pos: "VOL", alt: ["MC"], rating: 80 },
    { name: "Paul Groh", pos: "MC", alt: ["VOL"], rating: 79 },
    { name: "Mirosław Milewski", pos: "MC", alt: ["VOL"], rating: 79 },
    { name: "Norbert Meier", pos: "MEI", alt: ["MC"], rating: 78 },
    { name: "Manfred Kaltz", pos: "LD", alt: ["MD"], rating: 77 },
    { name: "Wolfgang Rolff", pos: "VOL", alt: ["MC"], rating: 77 },
    { name: "Bernd Wehmeyer", pos: "LE", alt: ["ME"], rating: 76 },
    { name: "Lars Bastrup", pos: "ATA", rating: 76 },
  ],
  "avi-1981": [
    { name: "Gary Shaw", pos: "ATA", rating: 82 },
    { name: "Ken McNaught", pos: "ZAG", rating: 81 },
    { name: "Des Bremner", pos: "MC", alt: ["VOL"], rating: 81 },
    { name: "Jimmy Rimmer", pos: "GOL", rating: 80 },
    { name: "Allan Evans", pos: "ZAG", rating: 79 },
    { name: "Gordon Cowans", pos: "MC", alt: ["VOL"], rating: 79 },
    { name: "Andy Blair", pos: "MEI", alt: ["MC"], rating: 79 },
    { name: "Dennis Mortimer", pos: "MC", alt: ["VOL"], rating: 78 },
    { name: "Tony Morley", pos: "PE", alt: ["ME"], rating: 78 },
    { name: "Colin Gibson", pos: "LE", alt: ["ME"], rating: 78 },
    { name: "David Geddis", pos: "ATA", rating: 77 },
    { name: "Peter Withe", pos: "ATA", rating: 76 },
    { name: "Nigel Spink", pos: "GOL", rating: 76 },
    { name: "Kenny Swain", pos: "LD", alt: ["MD"], rating: 76 },
    { name: "Gary Williams", pos: "LE", alt: ["ME"], rating: 76 },
    { name: "Pat Heard", pos: "VOL", alt: ["MC"], rating: 75 },
  ],
  "liv-1980": [
    { name: "Kenny Dalglish", pos: "ATA", rating: 89 },
    { name: "Graeme Souness", pos: "MC", alt: ["VOL", "MEI"], rating: 88 },
    { name: "Alan Hansen", pos: "ZAG", rating: 86 },
    { name: "Terry McDermott", pos: "MC", alt: ["VOL", "MEI"], rating: 86 },
    { name: "Ray Clemence", pos: "GOL", rating: 85 },
    { name: "Phil Neal", pos: "LD", alt: ["MD"], rating: 84 },
    { name: "Mark Lawrenson", pos: "ZAG", rating: 83 },
    { name: "Ronnie Whelan", pos: "MC", alt: ["VOL", "MEI"], rating: 82 },
    { name: "Sammy Lee", pos: "MC", alt: ["VOL"], rating: 81 },
    { name: "Craig Johnston", pos: "MEI", alt: ["MC"], rating: 80 },
    { name: "David Johnson", pos: "ATA", rating: 80 },
    { name: "Howard Gayle", pos: "PD", alt: ["MD"], rating: 77 },
    { name: "Bruce Grobbelaar", pos: "GOL", rating: 75 },
  ],
  "nfo-1979": [
    { name: "Trevor Francis", pos: "ATA", rating: 90 },
    { name: "John Robertson", pos: "PE", alt: ["ME"], rating: 89 },
    { name: "Peter Shilton", pos: "GOL", rating: 89 },
    { name: "Martin O'Neill", pos: "MEI", alt: ["MC", "ATA"], rating: 85 },
    { name: "Kenny Burns", pos: "ZAG", rating: 85 },
    { name: "Larry Lloyd", pos: "ZAG", rating: 83 },
    { name: "John McGovern", pos: "MC", alt: ["VOL", "MEI"], rating: 82 },
    { name: "Viv Anderson", pos: "LD", alt: ["MD"], rating: 82 },
    { name: "Ian Bowyer", pos: "MC", alt: ["VOL", "MEI"], rating: 82 },
    { name: "Frank Clark", pos: "LE", alt: ["ME"], rating: 81 },
    { name: "Garry Birtles", pos: "ATA", rating: 80 },
    { name: "Archie Gemmill", pos: "MC", alt: ["VOL"], rating: 79 },
    { name: "Hans van Breukelen", pos: "GOL", rating: 76 },
  ],
  "nfo-1978": [
    { name: "Peter Shilton", pos: "GOL", rating: 86 },
    { name: "Kenny Burns", pos: "ZAG", rating: 84 },
    { name: "John Robertson", pos: "PE", alt: ["ME"], rating: 82 },
    { name: "Larry Lloyd", pos: "ZAG", rating: 81 },
    { name: "Trevor Francis", pos: "ATA", rating: 80 },
    { name: "Ian Bowyer", pos: "MC", alt: ["VOL", "MEI"], rating: 80 },
    { name: "John McGovern", pos: "MC", alt: ["VOL"], rating: 79 },
    { name: "Tony Woodcock", pos: "ATA", rating: 79 },
    { name: "Viv Anderson", pos: "LD", alt: ["MD"], rating: 77 },
    { name: "Garry Birtles", pos: "ATA", rating: 76 },
    { name: "Frank Clark", pos: "LE", alt: ["ME"], rating: 75 },
    { name: "Archie Gemmill", pos: "MC", alt: ["VOL"], rating: 81 },
    { name: "John O'Hare", pos: "ATA", rating: 79 },
    { name: "Chris Woods", pos: "GOL", rating: 76 },
  ],
  "liv-1977": [
    { name: "Kenny Dalglish", pos: "ATA", rating: 90 },
    { name: "Graeme Souness", pos: "MC", alt: ["VOL", "MEI"], rating: 89 },
    { name: "Phil Neal", pos: "LD", alt: ["MD"], rating: 87 },
    { name: "Ray Clemence", pos: "GOL", rating: 87 },
    { name: "Alan Hansen", pos: "ZAG", rating: 84 },
    { name: "Terry McDermott", pos: "MC", alt: ["VOL"], rating: 84 },
    { name: "Emlyn Hughes", pos: "ZAG", rating: 83 },
    { name: "David Fairclough", pos: "ATA", rating: 82 },
    { name: "Jimmy Case", pos: "VOL", alt: ["MC"], rating: 82 },
    { name: "Joey Jones", pos: "LE", alt: ["ME"], rating: 81 },
    { name: "Steve Heighway", pos: "PE", alt: ["ME"], rating: 81 },
    { name: "David Johnson", pos: "ATA", rating: 80 },
    { name: "Bob Paisley", pos: "MEI", alt: ["MC"], rating: 76 },
    { name: "Bruce Grobbelaar", pos: "GOL", rating: 75 },
  ],
  "liv-1976": [
    { name: "Kevin Keegan", pos: "ATA", rating: 90 },
    { name: "Ray Clemence", pos: "GOL", rating: 89 },
    { name: "Phil Neal", pos: "LD", alt: ["MD"], rating: 87 },
    { name: "Terry McDermott", pos: "MC", alt: ["VOL", "MEI"], rating: 87 },
    { name: "Emlyn Hughes", pos: "ZAG", rating: 84 },
    { name: "Jimmy Case", pos: "VOL", alt: ["MC"], rating: 84 },
    { name: "Tommy Smith", pos: "ZAG", rating: 83 },
    { name: "David Fairclough", pos: "ATA", rating: 82 },
    { name: "Steve Heighway", pos: "PE", alt: ["ME"], rating: 82 },
    { name: "David Johnson", pos: "ATA", rating: 81 },
    { name: "Joey Jones", pos: "LE", alt: ["ME"], rating: 81 },
    { name: "Ray Kennedy", pos: "MC", alt: ["VOL"], rating: 81 },
    { name: "Ian Callaghan", pos: "MC", alt: ["VOL"], rating: 80 },
    { name: "Alan Hansen", pos: "ZAG", rating: 77 },
    { name: "Bob Bolder", pos: "GOL", rating: 75 },
  ],
  "bay-1975": [
    { name: "Franz Beckenbauer", pos: "ZAG", rating: 89 },
    { name: "Gerd Müller", pos: "ATA", rating: 89 },
    { name: "Sepp Maier", pos: "GOL", rating: 89 },
    { name: "Uli Hoeneß", pos: "ATA", rating: 86 },
    { name: "Karl-Heinz Rummenigge", pos: "ATA", rating: 83 },
    { name: "Hans-Georg Schwarzenbeck", pos: "ZAG", rating: 83 },
    { name: "Paul Breitner", pos: "VOL", alt: ["LE"], rating: 83 },
    { name: "Jupp Kapellmann", pos: "VOL", alt: ["MC"], rating: 81 },
    { name: "Conny Torstensson", pos: "ATA", rating: 80 },
    { name: "Bernd Dürnberger", pos: "MC", alt: ["VOL"], rating: 80 },
    { name: "Franz Roth", pos: "MC", alt: ["VOL"], rating: 79 },
    { name: "Johnny Hansen", pos: "LD", alt: ["MD"], rating: 79 },
    { name: "Walter Junghans", pos: "GOL", rating: 75 },
  ],
  "bay-1974": [
    { name: "Franz Beckenbauer", pos: "ZAG", rating: 89 },
    { name: "Gerd Müller", pos: "ATA", rating: 94 },
    { name: "Sepp Maier", pos: "GOL", rating: 89 },
    { name: "Uli Hoeneß", pos: "ATA", rating: 88 },
    { name: "Paul Breitner", pos: "VOL", alt: ["LE"], rating: 84 },
    { name: "Hans-Georg Schwarzenbeck", pos: "ZAG", rating: 83 },
    { name: "Franz Roth", pos: "MC", alt: ["VOL", "MEI"], rating: 82 },
    { name: "Jupp Kapellmann", pos: "VOL", alt: ["MC"], rating: 81 },
    { name: "Conny Torstensson", pos: "ATA", rating: 80 },
    { name: "Bernd Dürnberger", pos: "MC", alt: ["VOL"], rating: 80 },
    { name: "Johnny Hansen", pos: "LD", alt: ["MD"], rating: 79 },
    { name: "Karl-Heinz Rummenigge", pos: "ATA", rating: 77 },
    { name: "Walter Junghans", pos: "GOL", rating: 75 },
  ],
  "bay-1973": [
    { name: "Franz Beckenbauer", pos: "ZAG", rating: 99 },
    { name: "Gerd Müller", pos: "ATA", rating: 95 },
    { name: "Sepp Maier", pos: "GOL", rating: 88 },
    { name: "Paul Breitner", pos: "VOL", alt: ["LE"], rating: 88 },
    { name: "Uli Hoeneß", pos: "ATA", rating: 84 },
    { name: "Hans-Georg Schwarzenbeck", pos: "ZAG", rating: 82 },
    { name: "Franz Roth", pos: "MC", alt: ["VOL", "MEI"], rating: 82 },
    { name: "Conny Torstensson", pos: "ATA", rating: 80 },
    { name: "Jupp Kapellmann", pos: "VOL", alt: ["MC"], rating: 79 },
    { name: "Johnny Hansen", pos: "LD", alt: ["MD"], rating: 79 },
    { name: "Bernd Dürnberger", pos: "MC", alt: ["VOL"], rating: 78 },
    { name: "Katsche Schwarzenbeck", pos: "ZAG", rating: 77 },
    { name: "Walter Junghans", pos: "GOL", rating: 75 },
  ],
  "aja-1972": [
    { name: "Johan Cruyff", pos: "ATA", alt: ["MEI"], rating: 99 },
    { name: "Johan Neeskens", pos: "MC", alt: ["VOL"], rating: 90 },
    { name: "Johnny Rep", pos: "PD", alt: ["MD"], rating: 87 },
    { name: "Piet Keizer", pos: "PE", alt: ["ME"], rating: 87 },
    { name: "Ruud Krol", pos: "LE", alt: ["ME"], rating: 85 },
    { name: "Arie Haan", pos: "VOL", alt: ["MC"], rating: 84 },
    { name: "Horst Blankenburg", pos: "ZAG", rating: 84 },
    { name: "Barry Hulshoff", pos: "ZAG", rating: 83 },
    { name: "Heinz Stuy", pos: "GOL", rating: 82 },
    { name: "Gerrie Mühren", pos: "MC", alt: ["VOL"], rating: 82 },
    { name: "Wim Suurbier", pos: "LD", alt: ["MD"], rating: 82 },
    { name: "Henk Groot", pos: "ATA", rating: 78 },
    { name: "Ruud Suurendonk", pos: "ATA", rating: 77 },
    { name: "Jan Mulder", pos: "ATA", rating: 76 },
    { name: "Fred Schaub", pos: "MEI", alt: ["MC"], rating: 75 },
  ],
  "aja-1971": [
    { name: "Johan Cruyff", pos: "ATA", alt: ["MEI"], rating: 97 },
    { name: "Johan Neeskens", pos: "MC", alt: ["VOL"], rating: 89 },
    { name: "Piet Keizer", pos: "PE", alt: ["ME"], rating: 88 },
    { name: "Ruud Krol", pos: "LE", alt: ["ME"], rating: 86 },
    { name: "Johnny Rep", pos: "PD", alt: ["MD"], rating: 83 },
    { name: "Arie Haan", pos: "VOL", alt: ["MC"], rating: 83 },
    { name: "Barry Hulshoff", pos: "ZAG", rating: 83 },
    { name: "Horst Blankenburg", pos: "ZAG", rating: 82 },
    { name: "Wim Suurbier", pos: "LD", alt: ["MD"], rating: 82 },
    { name: "Gerrie Mühren", pos: "MC", alt: ["VOL"], rating: 81 },
    { name: "Heinz Stuy", pos: "GOL", rating: 81 },
    { name: "Sjaak Swart", pos: "PD", alt: ["MD"], rating: 80 },
    { name: "Henk Groot", pos: "ATA", rating: 77 },
    { name: "Jan Mulder", pos: "ATA", rating: 77 },
    { name: "Fred Schaub", pos: "MEI", alt: ["MC"], rating: 75 },
  ],
  "aja-1970": [
    { name: "Johan Cruyff", pos: "MEI", rating: 95 },
    { name: "Velibor Vasović", pos: "ZAG", rating: 83 },
    { name: "Heinz Stuy", pos: "GOL", rating: 82 },
    { name: "Sjaak Swart", pos: "PD", alt: ["MD"], rating: 82 },
    { name: "Piet Keizer", pos: "PE", alt: ["ME"], rating: 81 },
    { name: "Johan Neeskens", pos: "MC", alt: ["VOL"], rating: 80 },
    { name: "Barry Hulshoff", pos: "ZAG", rating: 79 },
    { name: "Gerrie Mühren", pos: "MC", alt: ["VOL"], rating: 79 },
    { name: "Arie Haan", pos: "VOL", alt: ["MC"], rating: 78 },
    { name: "Wim Suurbier", pos: "LD", alt: ["MD"], rating: 77 },
    { name: "Dick van Dijk", pos: "ATA", rating: 77 },
    { name: "Ruud Krol", pos: "LE", alt: ["ME"], rating: 76 },
    { name: "Horst Blankenburg", pos: "ZAG", rating: 75 },
    { name: "Ruud Suurendonk", pos: "ATA", rating: 77 },
    { name: "Theo van Duivenbode", pos: "LE", alt: ["ME"], rating: 77 },
  ],
  "fey-1969": [
    { name: "Ove Kindvall", pos: "ATA", rating: 90 },
    { name: "Wim Jansen", pos: "VOL", alt: ["MC"], rating: 87 },
    { name: "Willem van Hanegem", pos: "MC", alt: ["VOL"], rating: 87 },
    { name: "Rinus Israël", pos: "ZAG", rating: 86 },
    { name: "Theo Laseroms", pos: "ZAG", rating: 85 },
    { name: "Franz Hasil", pos: "MEI", alt: ["MC"], rating: 83 },
    { name: "Eddy Pieters Graafland", pos: "GOL", rating: 83 },
    { name: "Coen Moulijn", pos: "PE", alt: ["ME"], rating: 82 },
    { name: "Theo van Duivenbode", pos: "LE", alt: ["ME"], rating: 82 },
    { name: "Ruud Geels", pos: "ATA", rating: 81 },
    { name: "Henk Wery", pos: "PD", alt: ["MD"], rating: 80 },
    { name: "Joop van Daele", pos: "ZAG", rating: 80 },
    { name: "Piet Romeijn", pos: "MC", alt: ["VOL"], rating: 78 },
    { name: "Eddy Treijtel", pos: "GOL", rating: 75 },
  ],
  "mil-1968": [
    { name: "Gianni Rivera", pos: "MEI", alt: ["MC"], rating: 92 },
    { name: "Pierino Prati", pos: "ATA", rating: 89 },
    { name: "Karl-Heinz Schnellinger", pos: "ZAG", rating: 86 },
    { name: "Giovanni Trapattoni", pos: "VOL", alt: ["MC"], rating: 86 },
    { name: "Angelo Anquilletti", pos: "LD", alt: ["MD"], rating: 84 },
    { name: "Roberto Rosato", pos: "ZAG", rating: 83 },
    { name: "Fabio Cudicini", pos: "GOL", rating: 83 },
    { name: "Kurt Hamrin", pos: "PD", alt: ["MD"], rating: 82 },
    { name: "Nestor Combin", pos: "ATA", rating: 81 },
    { name: "Giovanni Lodetti", pos: "MC", alt: ["VOL"], rating: 81 },
    { name: "Saul Malatrasi", pos: "ZAG", rating: 80 },
    { name: "Giuseppe Sabadini", pos: "LD", alt: ["MD"], rating: 78 },
    { name: "Giovanni Morelli", pos: "MC", alt: ["VOL"], rating: 77 },
    { name: "Giorgio Morini", pos: "ZAG", rating: 76 },
  ],
  "mun-1967": [
    { name: "George Best", pos: "ATA", alt: ["MEI", "PD"], rating: 96 },
    { name: "Bobby Charlton", pos: "MEI", alt: ["MC"], rating: 90 },
    { name: "Denis Law", pos: "ATA", rating: 89 },
    { name: "Nobby Stiles", pos: "VOL", alt: ["MC"], rating: 86 },
    { name: "Alex Stepney", pos: "GOL", rating: 85 },
    { name: "Bill Foulkes", pos: "ZAG", rating: 83 },
    { name: "Pat Crerand", pos: "MC", alt: ["VOL"], rating: 82 },
    { name: "Tony Dunne", pos: "LE", alt: ["ME"], rating: 82 },
    { name: "Shay Brennan", pos: "LD", alt: ["MD"], rating: 82 },
    { name: "John Aston Jr", pos: "PE", alt: ["ME"], rating: 81 },
    { name: "Brian Kidd", pos: "ATA", rating: 81 },
    { name: "David Sadler", pos: "ZAG", rating: 80 },
    { name: "John Fitzpatrick", pos: "LD", alt: ["MD"], rating: 78 },
    { name: "Wilf McGuinness", pos: "VOL", alt: ["MC"], rating: 77 },
    { name: "Jimmy Rimmer", pos: "GOL", rating: 75 },
  ],
  "cel-1966": [
    { name: "Jimmy Johnstone", pos: "PD", alt: ["MD"], rating: 90 },
    { name: "Billy McNeill", pos: "ZAG", rating: 89 },
    { name: "Bobby Murdoch", pos: "MC", alt: ["VOL", "MEI"], rating: 87 },
    { name: "Tommy Gemmell", pos: "LD", alt: ["MD"], rating: 87 },
    { name: "Stevie Chalmers", pos: "ATA", rating: 84 },
    { name: "Bertie Auld", pos: "MC", alt: ["VOL", "MEI"], rating: 84 },
    { name: "John Clark", pos: "VOL", alt: ["MC"], rating: 83 },
    { name: "Willie Wallace", pos: "ATA", rating: 83 },
    { name: "Ronnie Simpson", pos: "GOL", rating: 82 },
    { name: "Jim Craig", pos: "LD", alt: ["MD"], rating: 82 },
    { name: "Bobby Lennox", pos: "PE", alt: ["ME"], rating: 81 },
    { name: "John Hughes", pos: "ATA", rating: 80 },
    { name: "Charlie Gallagher", pos: "MC", alt: ["VOL"], rating: 78 },
    { name: "John Fallon", pos: "GOL", rating: 75 },
  ],
  "rm-1965": [
    { name: "Francisco Gento", pos: "PE", alt: ["ME"], rating: 89 },
    { name: "Pirri", pos: "MC", alt: ["VOL", "MEI"], rating: 88 },
    { name: "Amancio Amaro", pos: "PD", alt: ["MD"], rating: 88 },
    { name: "Manuel Sanchís Sr.", pos: "ZAG", rating: 85 },
    { name: "Ignacio Zoco", pos: "VOL", alt: ["MC"], rating: 83 },
    { name: "Manuel Velázquez", pos: "MC", alt: ["VOL", "MEI"], rating: 83 },
    { name: "Antonio Betancort", pos: "GOL", rating: 82 },
    { name: "Fernando Serena", pos: "ATA", rating: 81 },
    { name: "Pedro de Felipe", pos: "ZAG", rating: 81 },
    { name: "Ramón Grosso", pos: "MEI", alt: ["MC"], rating: 81 },
    { name: "Pachín", pos: "ZAG", rating: 80 },
    { name: "Felix Ruiz", pos: "PD", alt: ["MD"], rating: 79 },
    { name: "José Araquistáin", pos: "GOL", rating: 75 },
  ],
  "int-1964": [
    { name: "Sandro Mazzola", pos: "ATA", alt: ["MEI"], rating: 89 },
    { name: "Giacinto Facchetti", pos: "LE", alt: ["ME"], rating: 89 },
    { name: "Luis Suárez", pos: "ATA", rating: 89 },
    { name: "Tarcisio Burgnich", pos: "LD", alt: ["MD"], rating: 86 },
    { name: "Armando Picchi", pos: "ZAG", rating: 84 },
    { name: "Jair da Costa", pos: "PD", alt: ["MD"], rating: 83 },
    { name: "Giuliano Sarti", pos: "GOL", rating: 83 },
    { name: "Aristide Guarneri", pos: "ZAG", rating: 83 },
    { name: "Mario Corso", pos: "PE", alt: ["ME"], rating: 83 },
    { name: "Gianfranco Bedin", pos: "VOL", alt: ["MC"], rating: 82 },
    { name: "Joaquín Peiró", pos: "ATA", rating: 81 },
    { name: "Renato Cappellini", pos: "ATA", rating: 79 },
    { name: "Domenico Morelli", pos: "GOL", rating: 75 },
  ],
  "int-1963": [
    { name: "Luis Suárez", pos: "ATA", rating: 88 },
    { name: "Sandro Mazzola", pos: "ATA", alt: ["MEI"], rating: 88 },
    { name: "Giacinto Facchetti", pos: "LE", alt: ["ME"], rating: 88 },
    { name: "Armando Picchi", pos: "ZAG", rating: 87 },
    { name: "Jair da Costa", pos: "PD", alt: ["MD"], rating: 83 },
    { name: "Tarcisio Burgnich", pos: "LD", alt: ["MD"], rating: 83 },
    { name: "Giuliano Sarti", pos: "GOL", rating: 82 },
    { name: "Mario Corso", pos: "PE", alt: ["ME"], rating: 82 },
    { name: "Aristide Guarneri", pos: "ZAG", rating: 82 },
    { name: "Gianfranco Bedin", pos: "VOL", alt: ["MC"], rating: 80 },
    { name: "Joaquín Peiró", pos: "ATA", rating: 80 },
    { name: "Aurelio Milani", pos: "ATA", rating: 79 },
    { name: "Domenico Morelli", pos: "GOL", rating: 75 },
  ],
  "mil-1962": [
    { name: "José Altafini", pos: "ATA", rating: 89 },
    { name: "Gianni Rivera", pos: "MEI", alt: ["MC"], rating: 89 },
    { name: "Cesare Maldini", pos: "ZAG", alt: ["LE"], rating: 88 },
    { name: "Giovanni Trapattoni", pos: "VOL", alt: ["MC"], rating: 86 },
    { name: "Gino Pivatelli", pos: "ATA", rating: 84 },
    { name: "Karl-Heinz Schnellinger", pos: "ZAG", rating: 83 },
    { name: "Roberto David", pos: "ZAG", rating: 82 },
    { name: "Giorgio Ferrario", pos: "LD", alt: ["MD"], rating: 81 },
    { name: "Bruno Mora", pos: "PD", alt: ["MD"], rating: 81 },
    { name: "Giovanni Lodetti", pos: "MC", alt: ["VOL"], rating: 81 },
    { name: "Enrico Albertosi", pos: "GOL", rating: 80 },
    { name: "Amarildo", pos: "ATA", rating: 80 },
    { name: "Ghezzi", pos: "GOL", rating: 76 },
  ],
  "ben-1961": [
    { name: "Eusébio", pos: "ATA", rating: 95 },
    { name: "Germano", pos: "ZAG", rating: 83 },
    { name: "Mário João", pos: "ZAG", rating: 82 },
    { name: "Costa Pereira", pos: "GOL", rating: 81 },
    { name: "Fernando Cruz", pos: "VOL", alt: ["MC"], rating: 80 },
    { name: "Santana", pos: "MC", alt: ["VOL"], rating: 79 },
    { name: "Ângelo Martins", pos: "ZAG", rating: 79 },
    { name: "Mário Coluna", pos: "MC", alt: ["VOL"], rating: 79 },
    { name: "Cavém", pos: "PE", alt: ["ME"], rating: 79 },
    { name: "José Augusto", pos: "PD", alt: ["MD"], rating: 77 },
    { name: "Neto", pos: "ZAG", rating: 76 },
    { name: "Lúcio", pos: "LD", alt: ["MD"], rating: 83 },
    { name: "Alfredo Afonso", pos: "ATA", rating: 79 },
    { name: "Amaro", pos: "GOL", rating: 76 },
  ],
  "ben-1960": [
    { name: "Mário Coluna", pos: "MC", alt: ["VOL"], rating: 88 },
    { name: "José Águas", pos: "ATA", rating: 88 },
    { name: "Costa Pereira", pos: "GOL", rating: 87 },
    { name: "José Augusto", pos: "PD", alt: ["MD"], rating: 87 },
    { name: "Santana", pos: "MC", alt: ["VOL"], rating: 83 },
    { name: "Germano", pos: "ZAG", rating: 83 },
    { name: "Cavém", pos: "PD", alt: ["MD"], rating: 82 },
    { name: "Cruz", pos: "ZAG", rating: 82 },
    { name: "Mário João", pos: "LE", alt: ["ME"], rating: 81 },
    { name: "Lúcio", pos: "LD", alt: ["MD"], rating: 80 },
    { name: "António Simões", pos: "PE", alt: ["ME"], rating: 79 },
    { name: "Amaro", pos: "GOL", rating: 75 },
  ],
  "rm-1959": [
    { name: "Alfredo Di Stéfano", pos: "ATA", alt: ["MEI"], rating: 97 },
    { name: "Ferenc Puskás", pos: "ATA", alt: ["MEI"], rating: 97 },
    { name: "Francisco Gento", pos: "PE", alt: ["ME"], rating: 88 },
    { name: "Raymond Kopa", pos: "MEI", alt: ["MC", "ATA"], rating: 88 },
    { name: "José Santamaría", pos: "ZAG", rating: 84 },
    { name: "José María Zárraga", pos: "VOL", alt: ["MC"], rating: 82 },
    { name: "Marquitos", pos: "ZAG", rating: 82 },
    { name: "Enrique Mateos", pos: "ATA", rating: 81 },
    { name: "Luis del Sol", pos: "MC", alt: ["VOL", "MEI"], rating: 80 },
    { name: "Domingo Pérez", pos: "LD", alt: ["MD"], rating: 79 },
    { name: "Vicente Train", pos: "GOL", rating: 78 },
    { name: "Juan Santisteban", pos: "MC", alt: ["VOL"], rating: 76 },
    { name: "Araquistáin", pos: "GOL", rating: 75 },
  ],
  "rm-1958": [
    { name: "Alfredo Di Stéfano", pos: "ATA", alt: ["MEI"], rating: 95 },
    { name: "Francisco Gento", pos: "PE", alt: ["ME"], rating: 88 },
    { name: "Raymond Kopa", pos: "MEI", alt: ["MC", "ATA"], rating: 88 },
    { name: "Ferenc Puskás", pos: "ATA", alt: ["MEI"], rating: 93 },
    { name: "José Santamaría", pos: "ZAG", rating: 84 },
    { name: "José María Zárraga", pos: "VOL", alt: ["MC"], rating: 82 },
    { name: "Marquitos", pos: "ZAG", rating: 82 },
    { name: "Héctor Rial", pos: "MEI", alt: ["MC", "ATA"], rating: 82 },
    { name: "Enrique Mateos", pos: "ATA", rating: 80 },
    { name: "Domingo Pérez", pos: "LD", alt: ["MD"], rating: 79 },
    { name: "Vicente Train", pos: "GOL", rating: 78 },
    { name: "Juan Santisteban", pos: "MC", alt: ["VOL"], rating: 76 },
    { name: "Araquistáin", pos: "GOL", rating: 75 },
  ],
  "rm-1957": [
    { name: "Alfredo Di Stéfano", pos: "ATA", alt: ["MEI"], rating: 94 },
    { name: "Raymond Kopa", pos: "MEI", alt: ["MC", "ATA"], rating: 88 },
    { name: "Francisco Gento", pos: "PE", alt: ["ME"], rating: 88 },
    { name: "Héctor Rial", pos: "MEI", alt: ["MC", "ATA"], rating: 87 },
    { name: "José Santamaría", pos: "ZAG", rating: 84 },
    { name: "José María Zárraga", pos: "VOL", alt: ["MC"], rating: 83 },
    { name: "Marquitos", pos: "ZAG", rating: 82 },
    { name: "Enrique Mateos", pos: "ATA", rating: 81 },
    { name: "Miguel Muñoz", pos: "MC", alt: ["VOL", "MEI"], rating: 80 },
    { name: "Domingo Pérez", pos: "LD", alt: ["MD"], rating: 80 },
    { name: "Rogelio Domínguez", pos: "GOL", rating: 79 },
    { name: "Juan Santisteban", pos: "MC", alt: ["VOL"], rating: 76 },
    { name: "Araquistáin", pos: "GOL", rating: 75 },
  ],
  "rm-1956": [
    { name: "Alfredo Di Stéfano", pos: "ATA", alt: ["MEI"], rating: 94 },
    { name: "Francisco Gento", pos: "PE", alt: ["ME"], rating: 88 },
    { name: "Raymond Kopa", pos: "MEI", alt: ["MC", "ATA"], rating: 88 },
    { name: "Héctor Rial", pos: "MEI", alt: ["MC", "ATA"], rating: 87 },
    { name: "José María Zárraga", pos: "VOL", alt: ["MC"], rating: 83 },
    { name: "Marquitos", pos: "ZAG", rating: 82 },
    { name: "José Santamaría", pos: "ZAG", rating: 82 },
    { name: "Miguel Muñoz", pos: "MC", alt: ["VOL", "MEI"], rating: 81 },
    { name: "Enrique Mateos", pos: "ATA", rating: 80 },
    { name: "Rafael Lesmes", pos: "LE", alt: ["ME"], rating: 80 },
    { name: "Alonso", pos: "GOL", rating: 79 },
    { name: "Joseíto", pos: "PE", alt: ["ME"], rating: 78 },
    { name: "Juan Santisteban", pos: "MC", alt: ["VOL"], rating: 76 },
  ],
  "rm-1955": [
    { name: "Alfredo Di Stéfano", pos: "ATA", alt: ["MEI"], rating: 94 },
    { name: "Héctor Rial", pos: "MEI", alt: ["MC", "ATA"], rating: 89 },
    { name: "Francisco Gento", pos: "PE", alt: ["ME"], rating: 88 },
    { name: "Miguel Muñoz", pos: "MC", alt: ["VOL", "MEI"], rating: 86 },
    { name: "José María Zárraga", pos: "VOL", alt: ["MC"], rating: 83 },
    { name: "Marquitos", pos: "ZAG", rating: 83 },
    { name: "Rafael Lesmes", pos: "LE", alt: ["ME"], rating: 82 },
    { name: "Joseíto", pos: "PE", alt: ["ME"], rating: 81 },
    { name: "Juan Alonso", pos: "GOL", rating: 81 },
    { name: "Roque Olsen", pos: "PD", alt: ["MD"], rating: 81 },
    { name: "Atienza", pos: "ZAG", rating: 79 },
    { name: "Enrique Mateos", pos: "ATA", rating: 79 },
    { name: "Juan Santisteban", pos: "MC", alt: ["VOL"], rating: 76 },
  ],
};
