// Transport-agnostic game state for the local/online multiplayer modes.
//
// The whole match flow is a turn-based state machine driven by *events*. The
// reducer is pure: any randomness (the dice draw, the bracket seed, the
// semifinal pairing) is pre-generated by whoever is authoritative (the local
// client today; the PartyKit room later) and arrives as an event payload.
//
// The local hot-seat (useRoom -> useReducer) and a future networked transport
// both feed the SAME reducer, so behaviour stays identical across modes.

// NOTE: relative imports (not the "@/" alias) so this module also builds inside
// the PartyKit worker, which doesn't read Next's tsconfig path aliases.
import { FORMATIONS, type FormationName, type Player } from "../data";
import { type Phase, type Style } from "../sim";

export const REROLL_MAX = 3;

export type Stage = "lobby" | "menu" | "setup" | "draft" | "reveal" | "result";
export type Mode = "single" | "twoleg" | "tourney";

export type Placed = (Player | null)[];

// a connected participant in an online room (host, player, or — teamIdx null
// with no slot — a spectator)
export type RoomPlayer = {
  id: string;
  name: string;
  teamIdx: number | null;
  connected: boolean;
};

// who the local viewer is, for gating interactivity in the shared game render.
// myTeamIdx null means "controls everything" (the local hot-seat).
export type Seat = {
  playerId: string;
  isHost: boolean;
  myTeamIdx: number | null;
  isOnline: boolean;
};

export const LOCAL_SEAT: Seat = {
  playerId: "",
  isHost: true,
  myTeamIdx: null,
  isOnline: false,
};

export type TeamCfg = {
  name: string;
  formation: FormationName;
  style: Style;
  almanaque: boolean;
  placed: Placed;
};

// A matchup carries an i18n *key* (+ optional n) instead of a resolved string,
// so each client renders it in its own locale.
export type Matchup = {
  labelKey: string;
  labelN?: number;
  a: number;
  b: number;
  legs: 1 | 2;
  phase: Phase;
};

export type RoomState = {
  stage: Stage;
  mode: Mode;
  teams: TeamCfg[];
  // online presence (empty/ignored in the local hot-seat)
  players: RoomPlayer[];
  hostId: string;
  ready: string[]; // player ids who pressed "Pronto"
  // draft
  turn: number;
  dir: 1 | -1; // snake direction (4-player)
  turnPicks: number;
  draw: { nationId: string; cup: number } | null;
  rerolls: number[];
  // bracket / reveal
  queue: Matchup[];
  qi: number;
  legIdx: number;
  matchStarted: boolean;
  baseSeed: number;
  results: { winner: number; loser: number }[];
  standings: number[] | null;
};

export type RoomEvent =
  | { t: "reset" }
  | { t: "back" }
  | { t: "playerJoin"; id: string; name: string } // server-only (on connect)
  | { t: "playerLeave"; id: string } // server-only (on disconnect)
  | { t: "setReady"; id: string; ready: boolean }
  | { t: "chooseMode"; mode: Mode }
  | { t: "patchTeam"; idx: number; patch: Partial<TeamCfg> }
  | { t: "chooseFormation"; idx: number; formation: FormationName }
  | { t: "startDraft" }
  | { t: "draw"; nationId: string; cup: number; reroll: boolean }
  | { t: "place"; player: Player; slot: number }
  | { t: "movePlaced"; from: number; to: number }
  | { t: "beginReveal"; baseSeed: number; queue: Matchup[] }
  | { t: "startMatch" }
  | { t: "nextLeg" }
  | { t: "finishMatchup"; winner: number };

// ----- helpers ----------------------------------------------------------

export function emptyTeam(): TeamCfg {
  return {
    name: "",
    formation: "4-3-3",
    style: "equilibrado",
    almanaque: false,
    placed: new Array(FORMATIONS["4-3-3"].length).fill(null),
  };
}

export const slotsCount = (t: TeamCfg) => FORMATIONS[t.formation].length;
export const filledCount = (t: TeamCfg) => t.placed.filter(Boolean).length;
export const isFull = (t: TeamCfg) => filledCount(t) >= slotsCount(t);

export function withPlaced(placed: Placed, i: number, p: Player): Placed {
  const next = placed.slice();
  next[i] = p;
  return next;
}

export function initialRoom(): RoomState {
  return {
    stage: "menu",
    mode: "single",
    teams: [emptyTeam(), emptyTeam()],
    players: [],
    hostId: "",
    ready: [],
    turn: 0,
    dir: 1,
    turnPicks: 0,
    draw: null,
    rerolls: [REROLL_MAX, REROLL_MAX],
    queue: [],
    qi: 0,
    legIdx: 0,
    matchStarted: false,
    baseSeed: 0,
    results: [],
    standings: null,
  };
}

// advance the draft turn after a pick lands (snake order in the 4-player
// tourney, simple alternation otherwise). when every team is full the turn is
// left as-is — the authority kicks off the bracket via a beginReveal event.
function advanceDraft(s: RoomState): RoomState {
  const next = { ...s, turnPicks: 0 };
  if (s.teams.every(isFull)) return next;
  if (s.mode !== "tourney") return { ...next, turn: s.turn === 0 ? 1 : 0 };
  const n = s.teams.length;
  let d: 1 | -1 = s.dir;
  let nt = s.turn;
  for (let guard = 0; guard < n * 4; guard++) {
    const ni = nt + d;
    if (ni < 0 || ni >= n) d = d === 1 ? -1 : 1; // boundary: end team picks again
    else nt = ni;
    if (!isFull(s.teams[nt])) break;
  }
  return { ...next, dir: d, turn: nt };
}

function finishMatchup(s: RoomState, winner: number): RoomState {
  const m = s.queue[s.qi];
  const loser = winner === m.a ? m.b : m.a;
  const results = s.results.slice();
  results[s.qi] = { winner, loser };

  if (s.mode !== "tourney") {
    return { ...s, results, standings: [winner, loser], stage: "result" };
  }
  if (s.qi === 1) {
    // both semis done -> append the 3rd-place match and the final
    const r0 = results[0];
    const r1 = results[1];
    const queue: Matchup[] = [
      ...s.queue,
      { labelKey: "multi.local.thirdPlace", a: r0.loser, b: r1.loser, legs: 1, phase: "PLAYOFF" },
      { labelKey: "multi.local.finalLabel", a: r0.winner, b: r1.winner, legs: 1, phase: "FINAL" },
    ];
    return { ...s, results, queue, qi: 2, legIdx: 0, matchStarted: false };
  }
  if (s.qi === 3) {
    const third = results[2];
    return {
      ...s,
      results,
      standings: [winner, loser, third.winner, third.loser],
      stage: "result",
    };
  }
  return { ...s, results, qi: s.qi + 1, legIdx: 0, matchStarted: false };
}

export function reducer(s: RoomState, e: RoomEvent): RoomState {
  switch (e.t) {
    case "reset":
      // keep who's in the room (online), reset the game itself; online returns
      // to the lobby, the local hot-seat to its menu
      return {
        ...initialRoom(),
        players: s.players.map((p) => ({ ...p, teamIdx: null })),
        hostId: s.hostId,
        ready: [],
        stage: s.players.length ? "lobby" : "menu",
      };
    case "back":
      return { ...s, stage: "menu" };
    case "playerJoin": {
      const exists = s.players.some((p) => p.id === e.id);
      const players = exists
        ? s.players.map((p) => (p.id === e.id ? { ...p, name: e.name, connected: true } : p))
        : [...s.players, { id: e.id, name: e.name, teamIdx: null, connected: true }];
      return { ...s, players, hostId: s.hostId || e.id };
    }
    case "playerLeave":
      return {
        ...s,
        players: s.players.map((p) => (p.id === e.id ? { ...p, connected: false } : p)),
      };
    case "setReady":
      return {
        ...s,
        ready: e.ready ? [...new Set([...s.ready, e.id])] : s.ready.filter((id) => id !== e.id),
      };
    case "chooseMode": {
      const n = e.mode === "tourney" ? 4 : 2;
      // seat the first n connected players onto teams 0..n-1 (online); the rest
      // (and the empty local hot-seat) get no team
      const connected = s.players.filter((p) => p.connected);
      const players = s.players.map((p) => {
        const seatIdx = connected.findIndex((c) => c.id === p.id);
        return { ...p, teamIdx: seatIdx >= 0 && seatIdx < n ? seatIdx : null };
      });
      return {
        ...initialRoom(),
        players,
        hostId: s.hostId,
        mode: e.mode,
        stage: "setup",
        teams: Array.from({ length: n }, emptyTeam),
        rerolls: Array.from({ length: n }, () => REROLL_MAX),
      };
    }
    case "patchTeam":
      return {
        ...s,
        teams: s.teams.map((tm, i) => (i === e.idx ? { ...tm, ...e.patch } : tm)),
      };
    case "chooseFormation":
      return {
        ...s,
        teams: s.teams.map((tm, i) =>
          i === e.idx
            ? { ...tm, formation: e.formation, placed: new Array(FORMATIONS[e.formation].length).fill(null) }
            : tm
        ),
      };
    case "startDraft":
      return { ...s, stage: "draft" };
    case "draw": {
      const rerolls = e.reroll
        ? s.rerolls.map((v, i) => (i === s.turn ? Math.max(0, v - 1) : v))
        : s.rerolls;
      return { ...s, draw: { nationId: e.nationId, cup: e.cup }, rerolls };
    }
    case "place": {
      const teams = s.teams.map((tm, i) =>
        i === s.turn ? { ...tm, placed: withPlaced(tm.placed, e.slot, e.player) } : tm
      );
      const picksPerTurn = s.mode === "tourney" ? 3 : 1;
      const picks = s.turnPicks + 1;
      const placed = { ...s, teams, draw: null, turnPicks: picks };
      if (picks >= picksPerTurn || isFull(teams[s.turn])) return advanceDraft(placed);
      return placed;
    }
    case "movePlaced":
      return {
        ...s,
        teams: s.teams.map((tm, i) => {
          if (i !== s.turn) return tm;
          const placed = tm.placed.slice();
          placed[e.to] = placed[e.from];
          placed[e.from] = null;
          return { ...tm, placed };
        }),
      };
    case "beginReveal":
      return {
        ...s,
        stage: "reveal",
        baseSeed: e.baseSeed,
        queue: e.queue,
        qi: 0,
        legIdx: 0,
        matchStarted: false,
        results: [],
      };
    case "startMatch":
      return { ...s, matchStarted: true };
    case "nextLeg":
      return { ...s, legIdx: s.legIdx + 1, matchStarted: false };
    case "finishMatchup":
      return finishMatchup(s, e.winner);
  }
}
